Indexing and Slicing allow us to extract specificc pieces of data from a larger dataset.

**INDEXING:**

In [2]:
import numpy as np
arr = np.array([10,20,30,40,50])

**Positive Indexing:**
Starts from left to right

In [3]:
print(arr[2])

30


**Negative Indexing:**
Starts from right to left

In [4]:
print(arr[-2])

40


**SLICING:**

In [5]:
print(arr[1:3])

[20 30]


**General Form:**
arr[ start : stop : step]

a. Start\
Where to begin

In [6]:
print(arr[2:])  #Start at index 2

[30 40 50]


b. Stop\
Where to stop

In [7]:
print(arr[:3])  #Stop at index 3

[10 20 30]


c. Step\
How many positions to jump

In [8]:
print(arr[::2])

[10 30 50]


**Reversing an Array:**\
One of the coolest use of slicing

In [9]:
print(arr[::-1])

[50 40 30 20 10]


**Why Do We Slice Rows and Columns?**\
In Data Science:\
Rows = observations\
Columns = features

**Example:**

| Name  | Age | Salary |
| ----- | --- | ------ |
| Ali   | 22  | 50000  |
| Sara  | 25  | 70000  |
| Ahmed | 30  | 90000  |


Lets make an array for the table above

In [15]:
arr = np.array([
    [22, 50000],
    [25, 70000],
    [30, 90000]
])
print(arr)

[[   22 50000]
 [   25 70000]
 [   30 90000]]


Sometimes we need only ages - Let's slice only ages

In [16]:
print(arr[:,0])

[22 25 30]


Sometimes we only need salaries - Let's slice only salaries

In [17]:
print(arr[:,1])

[50000 70000 90000]


Sometimes we need first few records - Let's slice 2 records 

In [18]:
print(arr[:2,])

[[   22 50000]
 [   25 70000]]


Sometimes we need only ages of first two records - Let's slice ages of first two records

In [19]:
print(arr[:2,0])

[22 25]


Sometimes we need only salaries of first two records - Let's slice salaries of first two records

In [20]:
print(arr[:2,1])

[50000 70000]


**Boolean Indexing - The Heart of Data Science**\
Now, we move beyond positions\
Instead of saying give me index 5\
We say, give me everyone older than 18

In [24]:
ages=np.array([17,22,23,21,19,14])
ages>=18

array([False,  True,  True,  True,  True, False])

Above is a Boolean Mask - very useful because it serves as a filter and unlike lists, it omits out the need for loops to validate

**Fancy Slicing**\
Normal slicing takes a range\
Fancy slicing lets you choose specific positions

In [32]:
print(arr[[1,2]]) #Fancy indexing rows

[[   25 70000]
 [   30 90000]]


In [28]:
print(arr[:,[0]]) #Fancy indexing columns

[[22]
 [25]
 [30]]
