**<center>Level 1: Beginner</center>**

\
**Problem 1: Monthly Sales Dataset**\
sales = np.array([\
    100,120,140,\
    160,180,200,\
    220,240,260,\
    280,300,320\
])\
**Tasks:**\
1.	Reshape into 4 quarters × 3 months.\
2.	Find total annual sales.\
3.	Find average monthly sales.\
4.	Find highest sale.\
5.	Find lowest sale.


In [2]:
import numpy as np
sales = np.array([
[100,120,140],
[160,180,200],
[220,240,260],
[280,300,320]
])
sales = sales.T
print(f"Reshaped : \n{sales}")
print(f"Total Annual Sales: {np.sum(sales)}")
print(f"Average Monthly Sales: {np.mean(sales,axis=0)}")
print(f"Highest Sale: {sales.max()}")
print(f"Lowest Sale: {sales.min()}")

Reshaped : 
[[100 160 220 280]
 [120 180 240 300]
 [140 200 260 320]]
Total Annual Sales: 2520
Average Monthly Sales: [120. 180. 240. 300.]
Highest Sale: 320
Lowest Sale: 100


\
**Problem 2: Temperature Monitoring**\
temps = np.array([\
    [25,27,24],\
    [30,32,31],\
    [20,22,19]\
])\
**Rows** = Cities\
**Columns** = Days\
**Tasks:**\
1.	Find average temperature per city.\
2.	Find average temperature per day.\
3.	Find hottest temperature.\
4.	Find coldest temperature.\
5.	Find temperature range.

In [24]:
temps = np.array([
[25,27,24],
[30,32,31],
[20,22,19]
])
print(f"Average Temperature per city: {np.mean(temps,axis=1)}")
print(f"Average Temperature per day: {np.mean(temps,axis=0)}")
print(f"Hottest Temperature: {temps.max()}")
print(f"Coldest Temperature: {temps.min()}")
print(f"Temperature Range: {temps.max() - temps.min()}")

Average Temperature per city: [25.33333333 31.         20.33333333]
Average Temperature per day: [25.         27.         24.66666667]
Hottest Temperature: 32
Coldest Temperature: 19
Temperature Range: 13


\
**Problem 3: Employee Bonus**\
salary = np.array([\
    50000,\
    60000,\
    70000,\
    80000\
])\
**Tasks:**\
1.	Add a bonus of 5000 using vectorization.\
2.	Calculate average salary before bonus.\
3.	Calculate average salary after bonus.\
4.	Find salary standard deviation.\
5.	Convert salaries into a column vector.


In [32]:
salary = np.array([50000,60000,70000,80000])
updated_salary = salary + 5000
print(f"Bonus added: {updated_salary}")
print(f"Average salary before bonus: {np.mean(salary)}")
print(f"Average salary after bonus: {np.mean(updated_salary)}")
print(f"Salary standard deviation: {np.std(updated_salary)}")
salary.reshape(-1,1)

Bonus added: [55000 65000 75000 85000]
Average salary before bonus: 65000.0
Average salary after bonus: 70000.0
Salary standard deviation: 11180.339887498949


array([[50000],
       [60000],
       [70000],
       [80000]])

\
**Problem 4: Student Marks**\
marks = np.array([\
    [78,82,85],\
    [65,70,68],\
    [90,88,92]\
])\
**Rows** = Students\
**Columns** = Subjects\
**Tasks:**\
1.	Find average marks per student.\
2.	Find average marks per subject.\
3.	Find highest mark.\
4.	Find lowest mark.\
5.	Flatten the dataset.

In [39]:
marks = np.array([
[78,82,85],
[65,70,68],
[90,88,92]
])
print(f"Average marks per student: {np.mean(marks,axis=1)}")
print(f"Average marks per subject: {np.mean(marks,axis=0)}")
print(f"Highest mark: {marks.max()}")
print(f"Lowest mark: {marks.min()}")
print(f"Flattened array: {marks.reshape(1,-1)}")

Average marks per student: [81.66666667 67.66666667 90.        ]
Average marks per subject: [77.66666667 80.         81.66666667]
Highest mark: 92
Lowest mark: 65
Flattened array: [[78 82 85 65 70 68 90 88 92]]


\
**Problem 5: Website Traffic**\
traffic = np.arange(100,112)\
**Tasks:**\
1.	Reshape into 4 weeks × 3 days.\
2.	Calculate weekly averages.\
3.	Calculate daily averages.\
4.	Find total visitors.\
5.	Find standard deviation.

In [53]:
traffic = np.arange(100,112)
print(f"Array: {traffic}")
traffic = traffic.reshape(4,3)
print(f"Reshaped Array: \n{traffic}")
print(f"Weekly Averages: {np.mean(traffic,axis=1)}")
print(f"Daily Averages: {np.mean(traffic,axis=0)}")
print(f"Total Visitors: {np.sum(traffic)}")
print(f"Standard Deviation: {np.std(traffic)}")

Array: [100 101 102 103 104 105 106 107 108 109 110 111]
Reshaped Array: 
[[100 101 102]
 [103 104 105]
 [106 107 108]
 [109 110 111]]
Weekly Averages: [101. 104. 107. 110.]
Daily Averages: [104.5 105.5 106.5]
Total Visitors: 1266
Standard Deviation: 3.452052529534663


**<center>Level 2: Intermediate</center>**

\
**Problem 6: Retail Stores**\
sales = np.array([\
    [1200,1400,1600],\
    [2000,2200,2400],\
    [1500,1700,1900]\
])\
**Tasks:**\
1.	Increase all sales by 10%.\
2.	Find average sales per store.\
3.	Find average sales per month.\
4.	Find best-performing store.\
5.	Find best-performing month.

In [50]:
sales = np.array([
[1200,1400,1600],
[2000,2200,2400],
[1500,1700,1900]
],dtype=float)
sales += 0.1*sales
print(f"10% increased: \n",sales)
print(f"Average sales per store: {np.mean(sales,axis=1)}")
print(f"Average sales per month: {np.mean(sales,axis=0)}")
print(f"Best Performing store: {sales[np.sum(sales,axis=1)==np.sum(sales,axis=1).max()]}")
print(f"Best Performing month: \n{sales[:,np.sum(sales,axis=0)==np.sum(sales,axis=0).max()]}")

10% increased: 
 [[1320. 1540. 1760.]
 [2200. 2420. 2640.]
 [1650. 1870. 2090.]]
Average sales per store: [1540. 2420. 1870.]
Average sales per month: [1723.33333333 1943.33333333 2163.33333333]
Best Performing store: [[2200. 2420. 2640.]]
Best Performing month: 
[[1760.]
 [2640.]
 [2090.]]


\
**Problem 7: Machine Learning Feature Matrix**\
X = np.array([\
    [22,50000],\
    [25,70000],\
    [30,90000],\
    [21,45000]\
])\
**Tasks:**\
1.	Compute column means.\
2.	Center data using broadcasting.\
3.	Find column standard deviations.\
4.	Compute column variances.\
5.	Verify centered columns have mean ≈ 0.

In [63]:
X = np.array([
[22,50000],
[25,70000],
[30,90000],
[21,45000]
])
means = np.mean(X,axis=0)
print(f"Column Means: {means}")
print(f"Centered Data: {X - means}")
print(f"Column Standard Deviations: {np.std(X,axis=0)}")
print(f"Column Variance: {np.var(X,axis=0)}")
print(f"Mean of centered columns: {np.mean(X-means,axis=0)}")

Column Means: [2.450e+01 6.375e+04]
Centered Data: [[-2.500e+00 -1.375e+04]
 [ 5.000e-01  6.250e+03]
 [ 5.500e+00  2.625e+04]
 [-3.500e+00 -1.875e+04]]
Column Standard Deviations: [3.50000000e+00 1.78097586e+04]
Column Variance: [1.225000e+01 3.171875e+08]
Mean of centered columns: [0. 0.]


\
**Problem 8: Sensor Calibration**\
sensor = np.array([\
    [100,102,98],\
    [150,152,149],\
    [200,201,205]\
])\
**Calibration correction:**\
correction = np.array([\
    [1],\
    [2],\
    [-1]\
])\
**Tasks:**\
1.	Apply correction using broadcasting.\
2.	Compute average reading per sensor.\
3.	Compute standard deviation per sensor.\
4.	Find sensor with highest average.\
5.	Flatten corrected dataset.

In [72]:
sensor = np.array([
[100,102,98],
[150,152,149],
[200,201,205]
])
correction = np.array([
[1],
[2],
[-1]
])
sensor += correction
print(f"Corrected sensor data: \n{sensor}")
print(f"Average reading per sensor: {np.mean(sensor,axis=1)}")
print(f"Standard deviation per sensor: {np.std(sensor,axis=1)}")
print(f"Sensor with highest average: {sensor[np.mean(sensor,axis=1)==np.mean(sensor,axis=1).max(),:]}")
print(f"Flattened Corrected Dataset: {sensor.flatten()}")

Corrected sensor data: 
[[101 103  99]
 [152 154 151]
 [199 200 204]]
Average reading per sensor: [101.         152.33333333 201.        ]
Standard deviation per sensor: [1.63299316 1.24721913 2.1602469 ]
Sensor with highest average: [[199 200 204]]
Flattened Corrected Dataset: [101 103  99 152 154 151 199 200 204]


\
**Problem 9: Product Prices**\
prices = np.array([\
    100,150,200,\
    250,300,350\
])\
**Tasks:**\
1.	Reshape into 2×3.\
2.	Apply 15% discount.\
3.	Compute average price.\
4.	Compute median price.\
5.	Compute standard deviation.

In [82]:
prices = np.array([100,150,200,250,300,350])
prices = prices.reshape(2,-1)
print(f"Reshaped: \n{prices}")
prices = prices - 0.15*prices
print(f"Prices discounted: \n{prices}")
print(f"Average price: {np.mean(prices)}")
print(f"Median price: {np.median(prices)}")
print(f"Standard deviation: {np.std(prices)}")

Reshaped: 
[[100 150 200]
 [250 300 350]]
Prices discounted: 
[[ 85.  127.5 170. ]
 [212.5 255.  297.5]]
Average price: 191.25
Median price: 191.25
Standard deviation: 72.58256792554715


\
**Problem 10: Quarterly Revenue**\
q1 = np.array([100,120,140])\
q2 = np.array([150,170,190])\
q3 = np.array([200,220,240])\
q4 = np.array([250,270,290])\
**Tasks:**\
1.	Stack into one matrix.\
2.	Find revenue per quarter.\
3.	Find average revenue per product.\
4.	Find overall mean.\
5.	Transpose dataset.

In [13]:
q1 = np.array([100,120,140])
q2 = np.array([150,170,190])
q3 = np.array([200,220,240])
q4 = np.array([250,270,290])
year = np.vstack((q1,q2,q3,q4))
print(f"Stacked Matrix: \n{year}")
print(f"Revenue per quarter: {np.sum(year,axis=1)}")
print(f"Average Revenue per product: {np.mean(year,axis=0)}")
print(f"Overall Mean: {np.mean(year)}")
transpose = year.T
print(f"Transposed Dataset: \n{transpose}")

Stacked Matrix: 
[[100 120 140]
 [150 170 190]
 [200 220 240]
 [250 270 290]]
Revenue per quarter: [360 510 660 810]
Average Revenue per product: [175. 195. 215.]
Overall Mean: 195.0
Transposed Dataset: 
[[100 150 200 250]
 [120 170 220 270]
 [140 190 240 290]]


\
**<center>Level 3: Upper Intermediate</center>**

\
**Problem 11: Salary Analytics**\
salary = np.array([\
    45000,\
    50000,\
    52000,\
    55000,\
    58000,\
    60000,\
    62000,\
    250000\
])\
**Tasks:**\
1.	Compute mean salary.\
2.	Compute median salary.\
3.	Compute Q1, Q2, Q3.\
4.	Compute IQR.\
5.	Detect outliers using IQR rule.

In [24]:
salary = np.array([45000,50000,52000,55000,58000,60000,62000,250000])
print(f"Mean Salary: {np.mean(salary)}")
print(f"Median Salary: {np.median(salary)}")
q1 = np.percentile(salary,25)
q2 = np.percentile(salary,50)
q3 = np.percentile(salary,75)
print(f"Quartiles:\nQuartile 1: {q1}\nQuartile 2: {q2}\nQuartile 3: {q3}")
iqr = q3 - q1
print(f"Interquartile Range(IQR): {iqr}")
outliers = salary[(salary<q1-1.5*iqr) | (salary>q2+1.5*iqr)]
print(f"Outliers: {outliers}")

Mean Salary: 79000.0
Median Salary: 56500.0
Quartiles:
Quartile 1: 51500.0
Quartile 2: 56500.0
Quartile 3: 60500.0
Interquartile Range(IQR): 9000.0
Outliers: [250000]


\
**Problem 12: Exam Performance**\
scores = np.array([\
    [78,82,85],\
    [65,70,68],\
    [90,88,92],\
    [45,55,60],\
    [72,75,79]\
])\
**Tasks:**\
1.	Compute average score per student.\
2.	Compute average score per subject.\
3.	Compute std per subject.\
4.	Find top-performing student.\
5.	Find hardest subject (lowest mean).

In [33]:
scores = np.array([
[78,82,85],
[65,70,68],
[90,88,92],
[45,55,60],
[72,75,79]
])
print(f"Average Score per student: {np.mean(scores,axis=1)}")
print(f"Average Score per subject: {np.mean(scores,axis=0)}")
print(f"Standard Deviation per subject: {np.std(scores,axis=0)}")
print(f"Top performing student: {scores[np.sum(scores,axis=1)==np.sum(scores,axis=1).max(),:]}")
print(f"Hardest Subject(lowest mean): \n{scores[:,np.mean(scores,axis=0)==np.mean(scores,axis=0).max()]}")

Average Score per student: [81.66666667 67.66666667 90.         53.33333333 75.33333333]
Average Score per subject: [70.  74.  76.8]
Standard Deviation per subject: [14.95326051 11.296017   11.51347037]
Top performing student: [[90 88 92]]
Hardest Subject(lowest mean): 
[[85]
 [68]
 [92]
 [60]
 [79]]


\
**Problem 13: Correlation Study**\
hours = np.array([1,2,3,4,5,6])\
scores = np.array([40,50,60,70,80,90])\
**Tasks:**\
1.	Compute correlation matrix.\
2.	Extract actual correlation coefficient.\
3.	Interpret result.\
4.	Compute covariance matrix.

In [41]:
hours = np.array([1,2,3,4,5,6])
scores = np.array([40,50,60,70,80,90])
correlation = np.corrcoef(hours,scores)
print(f"Correlation Matrix: \n{correlation}")
print(f"Actual Correlation Coefficient: {correlation[0,1]}")
print(f"It's a perfect positive correlation")
covariance = np.cov(hours,scores)
print(f"Covariance Matrix: \n{covariance}")

Correlation Matrix: 
[[1. 1.]
 [1. 1.]]
Actual Correlation Coefficient: 1.0
It's a perfect positive correlation
Covariance Matrix: 
[[  3.5  35. ]
 [ 35.  350. ]]


\
**Problem 14: Store Performance Matrix**\
sales = np.array([\
    [100,200,300,400],\
    [150,250,350,450],\
    [120,220,320,420]\
])\
**Tasks:**\
1.	Compute quarterly means.\
2.	Compute store means.\
3.	Add quarterly incentives:\
bonus = np.array([10,20,30,40])\
using broadcasting.\
4.	Find store with highest average.\
5.	Find quarter with highest average.

In [52]:
sales = np.array([
[100,200,300,400],
[150,250,350,450],
[120,220,320,420]
])
print(f"Quarterly Means: {np.mean(sales,axis=0)}")
print(f"Store Means: {np.mean(sales,axis=1)}")
bonus = np.array([10,20,30,40])
sales += bonus
print(f"Bonus added sales:\n{sales}")
print(f"Store with highest average: {sales[np.mean(sales,axis=1)==np.mean(sales,axis=1).max(),:]}")
print(f"Quarter with highest average: \n{sales[:,np.mean(sales,axis=0)==np.mean(sales,axis=0).max()]}")

Quarterly Means: [123.33333333 223.33333333 323.33333333 423.33333333]
Store Means: [250. 300. 270.]
Bonus added sales:
[[110 220 330 440]
 [160 270 380 490]
 [130 240 350 460]]
Store with highest average: [[160 270 380 490]]
Quarter with highest average: 
[[440]
 [490]
 [460]]


\
**Problem 15: Data Transformation Pipeline**\
data = np.arange(1,25)\
Tasks:\
1.	Reshape into 4×6.\
2.	Transpose it.\
3.	Flatten it.\
4.	Reshape into 3×8.\
5.	Verify size remains unchanged throughout.

In [61]:
data = np.arange(1,25)
print(f"Original Array: {data}")
reshaped = data.reshape(4,-1)
print(f"Reshaped into 4 X 6:\n{reshaped}\nSize: {reshaped.size}")
transpose = reshaped.T
print(f"Transposed Array:\n{transpose}\nSize: {transpose.size}")
flattened = transpose.flatten()
print(f"Flattened Array: {flattened}\nSize: {flattened.size}")
again_reshaped = flattened.reshape(3,-1)
print(f"Reshaped into 3 X 8: \n{again_reshaped}\nSize: {again_reshaped.size}")

Original Array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
Reshaped into 4 X 6:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
Size: 24
Transposed Array:
[[ 1  7 13 19]
 [ 2  8 14 20]
 [ 3  9 15 21]
 [ 4 10 16 22]
 [ 5 11 17 23]
 [ 6 12 18 24]]
Size: 24
Flattened Array: [ 1  7 13 19  2  8 14 20  3  9 15 21  4 10 16 22  5 11 17 23  6 12 18 24]
Size: 24
Reshaped into 3 X 8: 
[[ 1  7 13 19  2  8 14 20]
 [ 3  9 15 21  4 10 16 22]
 [ 5 11 17 23  6 12 18 24]]
Size: 24


\
**<center>Level 4: Upper Intermediate</center>**

\
**Problem 16: Customer Spending Analysis**\
customers = np.array([\
    [22,2000],\
    [25,3000],\
    [30,4500],\
    [35,5000],\
    [40,7000]\
])\
**Columns:**\
Age | Monthly Spend\
**Tasks:**\
1.	Compute mean age.\
2.	Compute mean spending.\
3.	Compute correlation matrix.\
4.	Extract correlation coefficient.\
5.	Interpret relationship.

In [69]:
customers = np.array([
[22,2000],
[25,3000],
[30,4500],
[35,5000],
[40,7000]
])
age = customers[:,0]
spend = customers[:,1]
print(f"Mean Age: {np.mean(age)}")
print(f"Mean Spending: {np.mean(spend)}")
correlation = np.corrcoef(age,spend)
print(f"Correlation Matrix: \n{correlation}")
print(f"Actual Correlation Coefficient: {correlation[0,1]}")
print(f"It's a Strong Positive Relationship")

Mean Age: 30.4
Mean Spending: 4300.0
Correlation Matrix: 
[[1.         0.98624612]
 [0.98624612 1.        ]]
Actual Correlation Coefficient: 0.9862461181714405
It's a Strong Positive Relationship


\
**Problem 17: Regional Sales Analytics**\
sales = np.array([\
    [120,140,160],\
    [180,200,220],\
    [240,260,280],\
    [300,320,340]\
])\
**Rows** = Regions\
**Columns** = Months\
**Tasks:**\
1.	Compute monthly averages.\
2.	Compute regional averages.\
3.	Add monthly inflation adjustment:\
adjustment = np.array([5,10,15])\
using broadcasting.\
4.	Find strongest region.\
5.	Find most profitable month.

In [77]:
sales = np.array([
[120,140,160],
[180,200,220],
[240,260,280],
[300,320,340]
])
print(f"Monthly Averages: {np.mean(sales,axis=0)}")
print(f"Regional Averages: {np.mean(sales,axis=1)}")
adjustment = np.array([5,10,15])
sales += adjustment
print(f"Monthly Inflation Adjustment Added:\n{sales}")
print(f"Strongest Region: {sales[np.sum(sales,axis=1)==np.sum(sales,axis=1).max(),:]}")
print(f"Most Profitable Month: \n{sales[:,np.sum(sales,axis=0)==np.sum(sales,axis=0).max()]}")

Monthly Averages: [210. 230. 250.]
Regional Averages: [140. 200. 260. 320.]
Monthly Inflation Adjustment Added:
[[125 150 175]
 [185 210 235]
 [245 270 295]
 [305 330 355]]
Strongest Region: [[305 330 355]]
Most Profitable Month: 
[[175]
 [235]
 [295]
 [355]]


\
**Problem 18: Manufacturing Quality Control**\
measurements = np.array([\
    10,11,10,9,10,\
    11,10,12,9,10,\
    10,11,10,50\
])\
**Tasks:**\
1.	Compute mean.\
2.	Compute median.\
3.	Compute std.\
4.	Compute IQR.\
5.	Detect outliers.

In [82]:
measurements = np.array([10,11,10,9,10,11,10,12,9,10,10,11,10,50])
print(f"Mean: {np.mean(measurements)}")
print(f"Median: {np.median(measurements)}")
print(f"Standard Deviation: {np.std(measurements)}")
q1 = np.percentile(measurements,25)
q3 = np.percentile(measurements,75)
iqr = q3 - q1
print(f"Interquartile Range: {iqr}")
print(f"Outliers: {measurements[(measurements<q1-1.5*iqr)|(measurements>q3+1.5*iqr)]}")

Mean: 13.071428571428571
Median: 10.0
Standard Deviation: 10.271070925623272
Interquartile Range: 1.0
Outliers: [50]


\
**Problem 19: Multi-Store Revenue Comparison**\
storeA = np.array([100,120,140])\
storeB = np.array([150,170,190])\
storeC = np.array([200,220,240])\
**Tasks:**\
1.	Stack all stores.\
2.	Compute revenue per store.\
3.	Compute revenue per month.\
4.	Compute overall mean.\
5.	Determine best-performing store.

In [87]:
storeA = np.array([100,120,140])
storeB = np.array([150,170,190])
storeC = np.array([200,220,240])
data = np.vstack((storeA,storeB,storeC))
print(f"Stacked Store Data:\n{data}")
print(f"Revenue per Store: {np.sum(data,axis=1)}")
print(f"Revenue per month: {np.sum(data,axis=0)}")
print(f"Overall Mean: {np.mean(data)}")
print(f"Best Performing Store: {data[np.sum(data,axis=1)==np.sum(data,axis=1).max(),:]}")

Stacked Store Data:
[[100 120 140]
 [150 170 190]
 [200 220 240]]
Revenue per Store: [360 510 660]
Revenue per month: [450 510 570]
Overall Mean: 170.0
Best Performing Store: [[200 220 240]]


\
**Problem 20: Mini Industry Case Study**
A company records:\
data = np.array([\
    [22,50000,3],\
    [25,70000,5],\
    [30,90000,7],\
    [21,45000,2],\
    [35,120000,10]\
])\
**Columns:**\
Age | Salary | Experience\
Tasks:\
1.	Compute mean of each feature.\
2.	Compute median of each feature.\
3.	Compute std of each feature.\
4.	Center dataset using broadcasting.\
5.	Verify centered means ≈ 0.\
6.	Compute correlation matrix among all features.\
7.	Identify strongest positive correlation.\
8.	Reshape salary column into a column vector.\
9.	Stack Age and Experience only into a new matrix.\
10.	Flatten the centered dataset.

In [14]:
data = np.array([
[22,50000,3],
[25,70000,5],
[30,90000,7],
[21,45000,2],
[35,120000,10]
])
print(f"Mean of each feature: {np.mean(data,axis=0)}")
print(f"Median of each feature: {np.median(data, axis=0)}")
print(f"Standard Deviation of each feature: {np.std(data,axis=0)}")
means = np.mean(data,axis=0)
print(f"Means: {means}")
centered_data = data - means
print(f"Centered Dataset: \n{centered_data}")
print(f"Centered Means: {np.mean(centered_data,axis=0)}")
correlation = np.corrcoef(data,rowvar=False)
print(f"Correlation Matrix: \n{correlation}")
print(f"Strongest Positive Correlation: {correlation[2,1]}")
salary = data[:,1]
salary = salary.reshape(-1,1)
print(f"Salary Column reshaped to a column vector:\n{salary}")
age = data[:,0]
age = age.reshape(-1,1)
experience = data[:,2]
experience = experience.reshape(-1,1)
age_exp = np.hstack((age,experience))
print(f"Age and Experience Only: \n{age_exp}")
print(f"Flattened Centered Dataset: {centered_data.flatten()}")

Mean of each feature: [2.66e+01 7.50e+04 5.40e+00]
Median of each feature: [2.5e+01 7.0e+04 5.0e+00]
Standard Deviation of each feature: [5.23832034e+00 2.75680975e+04 2.87054002e+00]
Means: [2.66e+01 7.50e+04 5.40e+00]
Centered Dataset: 
[[-4.6e+00 -2.5e+04 -2.4e+00]
 [-1.6e+00 -5.0e+03 -4.0e-01]
 [ 3.4e+00  1.5e+04  1.6e+00]
 [-5.6e+00 -3.0e+04 -3.4e+00]
 [ 8.4e+00  4.5e+04  4.6e+00]]
Centered Means: [-1.42108547e-15  0.00000000e+00 -3.55271368e-16]
Correlation Matrix: 
[[1.         0.99715723 0.99489199]
 [0.99715723 1.         0.99828993]
 [0.99489199 0.99828993 1.        ]]
Strongest Positive Correlation: 0.9982899277088527
Salary Column reshaped to a column vector:
[[ 50000]
 [ 70000]
 [ 90000]
 [ 45000]
 [120000]]
Age and Experience Only: 
[[22  3]
 [25  5]
 [30  7]
 [21  2]
 [35 10]]
Flattened Centered Dataset: [-4.6e+00 -2.5e+04 -2.4e+00 -1.6e+00 -5.0e+03 -4.0e-01  3.4e+00  1.5e+04
  1.6e+00 -5.6e+00 -3.0e+04 -3.4e+00  8.4e+00  4.5e+04  4.6e+00]
