__1. Creating an array from a list__


a. 1D Array:

In [1]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)


[1 2 3 4 5]


b. 2D Array:

In [2]:
arr=np.array([
    [1,2,3],
    [2,4,6],
    [3,6,9]
])
print(arr)

[[1 2 3]
 [2 4 6]
 [3 6 9]]


__2. Create an array of Zeros__

a. 1D Array:

In [3]:
arr=np.zeros(5)
print(arr)

[0. 0. 0. 0. 0.]


b. 2D Array:

In [5]:
arr=np.zeros((3,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


__3. Creating an array of Ones__

a. 1D Array:

In [6]:
arr=np.ones(5)
print(arr)

[1. 1. 1. 1. 1.]


b. 2D Array:

In [10]:
arr=np.ones((3,2))
print(arr)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


__4. Creating an Empty Array__

In [11]:
arr=np.empty(5)
print(arr)

[1. 1. 1. 1. 1.]


**5. Creating an Array with a specific value**

a. 1D Array:

In [13]:
arr=np.full(5,68)
print(arr)

[68 68 68 68 68]


b. 2D Array:

In [14]:
arr=np.full((2,3),5)
print(arr)

[[5 5 5]
 [5 5 5]]


**6. Creating a sequence**

a. with max limit only

In [16]:
arr=np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


b. with both min and max limit

In [17]:
arr=np.arange(1,23)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22]


c. with step specified too

In [18]:
arr=np.arange(0,10,2)
print(arr)

[0 2 4 6 8]


**7. Creating evenly spaced numbers**

In [23]:
arr=np.linspace(0,10,5)

Reference to the above example:\
0 --> Start\
10 --> Stop\
5 --> Number of evenly spaced numbers in this interval

In [24]:
print(arr)

[ 0.   2.5  5.   7.5 10. ]


**8. Creating an identity matrix**

In [25]:
arr=np.eye(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


**9. Creating random array**

a. random values between 0 and 1

In [28]:
arr=np.random.random(5)
print(arr)

[0.59406135 0.36237155 0.80514046 0.76317653 0.16815295]


b. random integers within a given range

In [32]:
arr=np.random.randint(0,100,5)

Reference to the above example:\
0 --> Start\
100 --> Stop\
5 --> Size of array

In [33]:
print(arr)

[31 97 70  4 52]
