**<center>Broadcasting</center>**\
NumPy's ability to:\
Automatically expand smaller arrays so arithmetic can be performed with larger arrays.

**Broadcasting Rule # 1**\
Start comparing dimensions from the RIGHT.\
**Broadcasting Rule #2**\
Dimensions are compatible if: Equal OR One of them is 1(Because 1 can be expanded to any number with repititions to match the dimensions)

**a) Scalar Broadcasting:** Scalar is expanded in an array to match dimensions of the array it is supposed to be added with

In [2]:
import numpy as np
arr = np.array([
    [1,2,3],
    [4,5,6]
])
arr + 5  #5 is the scalar

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In the above example, the array's shape is (2,3). Hence, the scalar 5 is expanded to be contained in an array of shape(2,3)\
5 becomes\
[\
[5 5 5],\
[5 5 5]\
]\
Then, this is added with the given array which yields the output.

**b) Row Broadcasting:** Row vector is repeated downwards to match the dimensions of the array it is supposed to be added with

In [5]:
arr = np.array([
    [1,2,3],
    [4,5,6]
])
row = np.array([10,20,30])
arr + row

array([[11, 22, 33],
       [14, 25, 36]])

In the above example, the array's shape is (2,3), and the row vector has a shape of (3,) or simply (1,3). Hence the **row** needs to be expanded to 2.\
[ 10 20 30 ]\
becomes\
[\
[10 20 30]\
[10 20 30]\
]\
Then, it is added with the given array which yields the output

**c) Column Broadcasting:** Column vector is repeated sideways to match the dimensions of the array it is supposed to be added with

In [7]:
arr = np.array([
    [1,2,3],
    [4,5,6]
])
column = np.array([
    [10],
    [20]
])
arr + column

array([[11, 12, 13],
       [24, 25, 26]])

In the above example, the array's shape is (2,3), and the column vector has a shape of (2,1). Hence the **column** needs to be expanded to 3.\
[\
[ 10 ]\
[ 20 ]\
]\
becomes\
[\
[10 10 10]\
[20 20 20]\
]\
Then, it is added with the given array which yields the output

**Real Data Science Example 1**\
**Suppose:**\
temperatures = np.array([\
    [25,26,24],\
    [30,31,29],\
    [20,22,21]\
])\
**Rows:** Cities\
**Columns:** Days\
Suppose each city's thermometer is off by:\
correction = np.array([\
    [1],\
    [2],\
    [1]\
])\
**Add:**\
temperatures + correction\
Each city receives its own adjustment.

In [9]:
temperatures = np.array([
[25,26,24],
[30,31,29],
[20,22,21]
])
correction = np.array([
[1],
[2],
[1]
])
temperatures + correction

array([[26, 27, 25],
       [32, 33, 31],
       [21, 23, 22]])

**Real Data Science Example 2**\
**Feature Scaling**\
**Suppose:**\
X = np.array([\
    [22,50000],\
    [25,70000],\
    [30,90000]\
])\
**Columns:** Age | Salary\
**Mean values:**\
means = np.array([25,70000])\
**Subtract:** X - means\
Broadcasting automatically applies the correct mean to each column.\
This is done constantly in machine learning.

In [12]:
X = np.array([
[22,50000],
[25,70000],
[30,90000]
])
means = np.array([25,70000])
X - means

array([[    -3, -20000],
       [     0,      0],
       [     5,  20000]])

# <center>Professional Uses of Broadcasting</center>
You'll use broadcasting for:\
**1. Feature Scaling**\
X - mean\
**2. Normalization**\
(X - mean) / std\
**3. Image Processing**\
image * brightness_factor\
**4. Sensor Calibration**\
sensor_data + correction\
**5. Financial Modeling**\
revenue * tax_rates\
**6. Machine Learning**\
X @ W + b\
That + b works because of broadcasting.

# Challenge Set

**Challenge 1**\
Create a 3×4 sales matrix.\
Add a scalar bonus of 100 to every value using broadcasting.

In [14]:
arr = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
])
bonus = 100
arr + bonus

array([[101, 102, 103, 104],
       [105, 106, 107, 108],
       [109, 110, 111, 112]])

\
\
**Challenge 2**\
Create a 4×3 matrix.\
Create a row vector of shape (3,).\
Add it to the matrix.

In [16]:
arr = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9],
    [10,11,12]
])
row = np.array([2,4,6])
arr + row

array([[ 3,  6,  9],
       [ 6,  9, 12],
       [ 9, 12, 15],
       [12, 15, 18]])

\
\
**Challenge 3**\
Create a 4×3 matrix.\
Create a column vector of shape (4,1).\
Add it.

In [17]:
arr = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9],
    [10,11,12]
])
column = np.array([
    [1],
    [2],
    [3],
    [4]
])
arr + column

array([[ 2,  3,  4],
       [ 6,  7,  8],
       [10, 11, 12],
       [14, 15, 16]])

\
\
**Challenge 4**\
Without loops:\
ages = np.array([22,25,30,21])\
Convert to a column vector.

In [18]:
ages = np.array([22,25,30,21])
ages.reshape(-1,1)

array([[22],
       [25],
       [30],
       [21]])

\
\
**Challenge 5**\
Given:\
X = np.array([\
    [22,50000],\
    [25,70000],\
    [30,90000]\
])\
means = np.array([25,70000])\
Use broadcasting to center the dataset.

In [20]:
X = np.array([
[22,50000],
[25,70000],
[30,90000]
])
means = np.array([25,70000])
X - means

array([[    -3, -20000],
       [     0,      0],
       [     5,  20000]])