# <center>Linear Algebra for Data Science and Machine Learning</center>

**Part 1: Scalars, Vectors and Matrices**

**a) Scalar**: A number\
**b) Vector**: A 1D Array\
**c) Matrix**: An nd Array where n>1\
A matrix often represents:\
Entire datasets\
Images\
Transformations\
Feature tables

**Part 2: Vector Operations**

In [1]:
import numpy as np
a = np.array([1,2,3])
b = np.array([4,5,6])

**a) Vector Addition:**

In [2]:
a+b

array([5, 7, 9])

**b) Vector Subtraction:**

In [3]:
a-b

array([-3, -3, -3])

**c) Scalar Multiplication:**

In [4]:
a*10

array([10, 20, 30])

**Part 3: Dot Product**

$a \cdot b = \sum_{i=1}^{n} a_i b_i$

In [6]:
np.dot(a,b)

np.int64(32)

**Part 4: Matrix Multiplication:**

A * B returns element wise multiplication.\
For matrix multiplication,\
A @ B\
Or \
np.matmul(A,B)

In [7]:
A = np.array([
    [1,2],
    [3,4]
])

B = np.array([
    [5,6],
    [7,8]
])

A @ B

array([[19, 22],
       [43, 50]])

or

In [8]:
np.matmul(A,B)

array([[19, 22],
       [43, 50]])

**Insight:** Every element i.e., A[i][j] in the Product Matrix comes from the dot product of ith row of first matrix and jth column of second matrix.\
**Shape Rule:** While multiplying,\
Matrix A --> shape=(m,n)\
Matrix B --> shape=(n,p)\
The shape of product will be (m,p).\
**Eligibility Rule:** Multiplication is only possible if number of columns of first and rows of second are equal.

**Part 5: Tranpose in Linear Algebra**\
swapping of rows and columns

In [13]:
A = np.array([
    [1,2,3],
    [4,5,6]
])
print(f"Original Matrix:\n{A}")
print(f"Shape of Original Array: {A.shape}")
B = A.T
print(f"Transpose:\n{B}")
print(f"Shape of Transpose: {B.shape}")

Original Matrix:
[[1 2 3]
 [4 5 6]]
Shape of Original Array: (2, 3)
Transpose:
[[1 4]
 [2 5]
 [3 6]]
Shape of Transpose: (3, 2)


**Part 6: Identity Matrix**\
Identity Matrix behaves like number 1.

In [15]:
I = np.eye(3)
print(f"Identity Matrix:\n{I}")

Identity Matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


A @ I = A, where A is a matrix of same order as I

In [17]:
print(f"Matrix A:\n{A}")
print(f"A @ I:\n{A @ I}")

Matrix A:
[[1 2 3]
 [4 5 6]]
A @ I:
[[1. 2. 3.]
 [4. 5. 6.]]


**Part 7: Matrix Inverse**\
Like numbers, matrices have inverses too\
A @ inverse of A = I

In [23]:
print(f"Matrix A:\n{A}")
print(f"Inverse of A:\n{np.linalg.inv(A)}")
print(f"A @ Inverse of A:\n{np.round(A @ np.linalg.inv(A))}")

Matrix A:
[[1 2]
 [3 4]]
Inverse of A:
[[-2.   1. ]
 [ 1.5 -0.5]]
A @ Inverse of A:
[[1. 0.]
 [0. 1.]]


**Part 8: Determinant**\
A number associated with matrix which tells if a matrix is singular(not invertible) or non-singular(invertible)\
A matrix is singular if the determinant is equal to 0.\
A matrix is non-singular if the determinant is not equal to 0.

In [24]:
np.linalg.det(A)

np.float64(-2.0000000000000004)

In the above example, the determinant is not equal to 0, which means the given matrix is non-singular and hence, invertible.

**Part 9: Solving System of Equation**\
**Suppose:**\
x + y = 5\
2x + y = 8\
**In matrix form,**\
A = coefficient matrix(a matrix that consists of all the coefficients given with variables in the system of equations)\
b = constant matrix(a matrix that contains all the constants on the right hand sides of system of equations)\
**To solve this system of equations for values of x and y**\
np.linalg.solve(A,b)

In [25]:
A = np.array([
    [1,1],
    [2,1]
])

b = np.array([
    5,
    8
])
np.linalg.solve(A,b)

array([3., 2.])

**Output of the above code implies that:**\
x = 3\
y = 2

**Part 10: Norms**\
Norm is simply the length(magnitude) of a vector\
**What Does "Length" Mean?**\
Suppose you're standing at:\
(0,0)\
and walk to:\
(3,4)\
**Mathematically:**\
$d = \sqrt{(3-0)^2 + (4-0)^2} = 5$\
**Graphically**:
```text
      (3,4)
        *
       /|
      / |
     /  |
    /   |
   /    |
  *-----*
(0,0)  (3,0)
```
The horizontal movement is: 3\
The vertical movement is: 4\
The actual distance travelled is: 5\
While calculating the norm(length of a vector), remember that a vector always starts from (0,0).\
Hence, the formula becomes\
$\|\mathbf{v}\| = \sqrt{x^2 + y^2}$

In [28]:
v = np.array([3,4])
np.linalg.norm(v)

np.float64(5.0)

**Industry-Level Understanding**\
When you see:\
prediction = X @ W + b\
**you should recognize:**\
X = data matrix\
W = model weights\
b = bias\
@ = matrix multiplication\
'+'= broadcasting\
That's the skeleton of many machine learning models.