# <center>Random Numbers, Probability and Simulation</center>

**Why Randomness Matters?**\
Suppose you're building a fraud detection system.\
You might have:\
1,000 real fraud cases\
But you want to test your algorithm on:\
100,000 cases\
Instead of collecting more data, you can simulate it.\
Random number generation makes this possible.\

**1. Random Number Generator** 

In [2]:
import numpy as np
np.random.random()

0.35613170378575576

**2. Random Floats**\
Generate one random number between:\
0 and 1

In [2]:
np.random.random()

0.24284152058699904

Generate many:


In [5]:
np.random.random(3)

array([0.38545943, 0.65352409, 0.09015177])

Generate a 2D Matrix:

In [4]:
np.random.random((2,3))

array([[0.62998466, 0.68238645, 0.5447716 ],
       [0.37107002, 0.00416226, 0.07108121]])

**When Is This Used?**\
**Examples:**\
•	Simulating sensor noise\
•	Initializing ML model weights\
•	Testing algorithms

**3. Random Integers**\
generate random integers

In [7]:
np.random.randint(1,5)

1

Generate many:

In [8]:
np.random.randint(1,10,5)

array([4, 4, 2, 3, 6], dtype=int32)

Generate a 2D Matrix:

In [12]:
np.random.randint(1,5,(3,4))

array([[1, 2, 2, 3],
       [2, 4, 1, 4],
       [1, 4, 3, 2]], dtype=int32)

**Industry Example**\
Generate synthetic ages:\
ages = np.random.randint(18,65,1000)\
Creates 1000 fake customers.

**4. Reproducibility**\
**Suppose:**\
np.random.randint(1,10,5)\
Run again:\
Different result.\
Run again:\
Different result.\
This is bad for experiments.\
**Use:**\
np.random.seed(42)\
**Then:**\
np.random.randint(1,10,5)\
will always generate the same numbers.

In [14]:
np.random.seed(10)
np.random.randint(1,10,4)

array([5, 1, 2, 1], dtype=int32)

Try running above block again and again, You'll get the same output everytime

**Why Data Scientists Care**\
**Suppose:**\
Train Accuracy = 92%\
Your teammate should be able to reproduce your results.\
Seeds help achieve this.

**5. Random Choice**\
Choose random elements from existing data.

In [15]:
fruits = np.array(["Apple","Mango","Banana","Orange"])
np.random.choice(fruits)

np.str_('Mango')

Generate multiple:

In [25]:
np.random.choice(fruits,3)

array(['Mango', 'Mango', 'Orange'], dtype='<U6')

To avoid repition, use replace = False:

In [26]:
np.random.choice(fruits,3,replace=False)

array(['Apple', 'Orange', 'Banana'], dtype='<U6')

**Industry Usage**\
Sampling customers:\
sample = np.random.choice(customer_ids,size=100,replace=False)

**6. Shuffling**\
Mixes elements of an array and switches their positions

In [31]:
arr = np.array([1,2,3,4,5,6])
np.random.shuffle(arr)
print(arr)

[6 5 3 2 4 1]


Important: shuffle() modifies original array.

**7. Permutation**\
Similar to shuffle but returns a new array.\
Original remains unchanged

In [35]:
arr = np.array([1,2,3,4,5,6])
np.random.permutation(arr)

array([3, 4, 2, 5, 6, 1])

In [36]:
print(f"Original Unchanged Array: {arr}")

Original Unchanged Array: [1 2 3 4 5 6]


**8. Uniform Distribution**\
Generate values between bounds.

In [42]:
np.random.uniform(50,100,10)

array([67.3173575 , 52.15486781, 93.99575873, 88.16202936, 93.90483214,
       70.87545719, 80.27887822, 75.67333137, 79.8918324 , 63.11078306])

**9. Normal Distribution**\
Real-world data often follows a bell curve.\
**Examples:**\
•	Heights\
•	IQ scores\
•	Measurement errors\
•	Exam scores

In [46]:
np.random.normal(loc=50,scale=10,size=100)

array([47.21025647, 53.36971867, 44.66896571, 35.98422657, 57.22504401,
       51.16877089, 36.57265908, 35.32235644, 38.60948443, 53.6939594 ,
       40.7326613 , 52.93493828, 36.24217081, 47.43384033, 54.11926291,
       41.35813196, 43.0584439 , 36.59117696, 60.39977958, 45.09360479,
       50.30407755, 32.2116684 , 43.97290194, 50.52266499, 57.06558654,
       50.7703761 , 32.29660693, 49.49859364, 49.83877113, 53.92225086,
       55.01636536, 40.72637902, 49.28299614, 56.31838828, 57.7041897 ,
       40.72092499, 42.41275031, 52.45330708, 46.32885336, 47.12415548,
       58.46674923, 51.49455495, 55.82894819, 56.13893072, 39.28152052,
       57.38393363, 49.53555135, 33.9049963 , 52.37045621, 52.36444269,
       53.59255488, 44.83469813, 59.8502677 , 42.20741953, 46.04115846,
       60.83184851, 54.93294453, 52.32256999, 67.28388586, 47.66257402,
       31.52918402, 52.17893947, 45.99232033, 46.5598535 , 41.00378166,
       39.70700503, 43.65445933, 53.91864483, 38.24189841, 54.93

**Meaning:**\
Mean = loc = 50\
Std = scale = 10\
size = Generate 1000 values\
**Why Normal Distribution Matters**\
Many ML assumptions are based on approximately normal data.\
This is seen repeatedly in statistics.

**10. Random Data Sampling:**


In [48]:
population = np.arange(10000)
sample = np.random.choice(
    population,
    size=500,
    replace=False
)
print(sample)

[6142 6322 5155 4968 8706 7761 4221 9633 5629 8000 7936 6372 3981 5530
 3664 5501 9208  145 7247 5295 1957  574 4510 2822 7184 4085 2317 1050
 9474 7237  551 9438 8331 3062 5657 9794  976 5527 1925 4938 2995 9699
 2998 7629 9448 6223 9940 9841  915 9507 3520 9909 6805 1052 2271 5383
 8687 9554 2732 4185 7636 6380 8536 8710 9795 2747 4479 3145 2461  663
 5103 9609 1517 4099 9217 5955 3758 3273 9388 9744 4155  418 6275 2372
 1841 3015 8358 5174 9947 1747 5180 3595 5645 4017 8394 9073 3476 2448
 4813  443 7042 8367  800 4544 3383  502 7328 4181 3519 1912 2624 2490
 8513 2244  972 4830 9778  286  680 6556  239 9421 1152  575 2406 6150
 6854 7882 5977 7963 8782 7863  100 8852 1796  254 1814 7388 4299 5384
 1855 4672 8811 9185 1802 1871 4951 6727 3838 3392 1509 6229  151 4536
 5590 9693 1876 5217 1279 8728 8259 3524 3682 6172 2028 7527 7797 3609
 5652 6364 7867 2711 6628 5173 8510 4520 6715 9734 9662 2627 5161 7408
  917 4654 2999 2983 6518 3344 6535  824 7682 7812 2117 4082 1862 3123
 4219 

**This simulates:**\
Surveying 500 people out of 10,000

**11. Simple Probability Simulation**\
Let's estimate probability

In [51]:
tosses = np.random.choice(
    ["H","T"],
    size=10000
)
#np.sum(tosses=="H")
np.mean(tosses=="H")

np.float64(0.4945)

**Why This Is Powerful**\
Instead of solving mathematically:\
P(event)\
you can simulate millions of experiments.\
This is called:**Monte Carlo Simulation**

**12. Monte Carlo Example**\
Estimate probability of rolling a 6.

In [54]:
dice = np.random.randint(1,7,100000)
np.mean(dice==6)

np.float64(0.16731)

**13. Random Dataset Creation**\
Create fake customer data:

In [7]:
ages = np.random.randint(18,65,10)
salary = np.random.normal(60000,15000,10)
#combine
data = np.column_stack((ages,salary))
np.set_printoptions(suppress=True)
print(data)

[[   56.         58900.0110531 ]
 [   35.         79477.66479238]
 [   33.         56852.06570971]
 [   59.         59739.62394978]
 [   31.         54868.59076417]
 [   29.         47068.3126875 ]
 [   29.         81418.8912735 ]
 [   57.         70549.30368156]
 [   47.         70655.21801076]
 [   59.         38795.85842836]]


This is common for testing ML pipelines.

**Industry Mini Project**\
**Create:**\
1000 customers\
**with:**\
Random age\
Random salary\
Random spending score\
**Then:**\
Compute means.\
Compute stds.\
Find correlation.\
Sample 100 customers.\
Shuffle data.\
Find probability salary > 80,000.\
Find probability age < 25.\
This resembles the first step of many real-world analytics projects.

In [14]:
age = np.random.randint(16,60,1000)
salary = np.random.normal(50000,3000,1000)
spending = np.random.randint(1,6,1000)
customers = np.column_stack((age,salary,spending))
print(f"Means of age, salary and spending score: {np.mean(customers,axis=0)}")
print(f"Standard Deviations of age, salary and spending score: {np.std(customers,axis=0)}")
print(f"Correlation Matrix: \n{np.corrcoef(customers,rowvar=False)}")
indices = np.random.choice(500, size=100, replace=False)
sample = customers[indices]
np.set_printoptions(suppress=True)
print(f"Sample of 100 Customers:\n{sample}")
np.random.shuffle(sample)
print(f"Shuffled Sample:\n{sample}")
prob_salary_above_80000 = np.mean(salary > 80000)
print(f"Probability of salary > 80,000: {prob_salary_above_80000}")
prob_age_below_25 = np.mean(age < 25)
print(f"Probability of age below 25: {prob_age_below_25}")

Means of age, salary and spending score: [   36.933      50121.40524858     2.927     ]
Standard Deviations of age, salary and spending score: [  12.56696109 3115.53274113    1.4133899 ]
Correlation Matrix: 
[[1.         0.00625839 0.01227952]
 [0.00625839 1.         0.04711143]
 [0.01227952 0.04711143 1.        ]]
Sample of 100 Customers:
[[   50.         46855.2572562      2.        ]
 [   49.         52196.90946724     4.        ]
 [   51.         51493.29812931     3.        ]
 [   21.         51922.81652126     2.        ]
 [   24.         49822.39003309     3.        ]
 [   58.         52505.39784321     1.        ]
 [   26.         53994.75879005     1.        ]
 [   17.         47581.04733817     2.        ]
 [   58.         51656.47329754     1.        ]
 [   24.         50507.20040736     4.        ]
 [   37.         48005.52163718     1.        ]
 [   33.         51157.17465689     5.        ]
 [   53.         49410.57110242     1.        ]
 [   33.         50246.71945943   