**Array Attributes**


Creating 1D, 2D and 3D arrays to examine their attributes

In [19]:
import numpy as np
arr1d = np.array([2,3,4,5])
arr2d=np.array([
    [1,2,3],
    [2,3,4]
])
arr3d = np.array([
    [
        [1,2,3],
        [4,5,6]
    ],
    [
        [2,4,6],
        [8,10,12]
        ]
])

**1. Shape**\
tells us the size of array in each dimension

a. 1D Array:

In [20]:
print("Array: ",arr1d)
print("Shape: ",arr1d.shape)

Array:  [2 3 4 5]
Shape:  (4,)


b. 2D Array:

In [21]:
print("Array: \n",arr2d)
print("Shape: ",arr2d.shape)

Array: 
 [[1 2 3]
 [2 3 4]]
Shape:  (2, 3)


c. 3D Array:

In [22]:
print("Array: \n",arr3d)
print("Shape: ",arr3d.shape)

Array: 
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 2  4  6]
  [ 8 10 12]]]
Shape:  (2, 2, 3)


**2. ndim**\
Number of dimensions

In [24]:
print("Dimensions of 1D Array: ",arr1d.ndim)
print("Dimensions of 2D Array: ",arr2d.ndim)
print("Dimensions of 3D Array: ",arr3d.ndim)

Dimensions of 1D Array:  1
Dimensions of 2D Array:  2
Dimensions of 3D Array:  3


**3. size**\
Total number of elements in the array

In [26]:
print("Size of 1D Array we created: ",arr1d.size)
print("Size of 2D Array we created: ",arr2d.size)
print("Size of 3D Array we created: ",arr3d.size)

Size of 1D Array we created:  4
Size of 2D Array we created:  6
Size of 3D Array we created:  12


Fun Fact:\
Size of an array = Product of shape

In [29]:
print("Shape of 2D Array: ", arr2d.shape)
print("Size of that Array: ", arr2d.size)
print("Shape of 3D Array: ", arr3d.shape)
print("Size of that Array: ", arr3d.size)

Shape of 2D Array:  (2, 3)
Size of that Array:  6
Shape of 3D Array:  (2, 2, 3)
Size of that Array:  12


 **4. dtype**\
 Data type of elements

In [32]:
print("Data type of elements of 1d Array: ", arr1d.dtype)
print("Data type of elements of 2d Array: ", arr2d.dtype)
print("Data type of elements of 3d Array: ", arr3d.dtype)

Data type of elements of 1d Array:  int64
Data type of elements of 2d Array:  int64
Data type of elements of 3d Array:  int64


**5. itemsize**\
Memory occupied by one element(in bytes)

In [34]:
print("Size of each element in our 1D Array: ",arr1d.itemsize)
print("Size of each element in our 2D Array: ",arr2d.itemsize)
print("Size of each element in our 3D Array: ",arr3d.itemsize)

Size of each element in our 1D Array:  8
Size of each element in our 2D Array:  8
Size of each element in our 3D Array:  8


**6. nbytes**\
Memory occupied by entire array

In [37]:
print("Memory occupied by 1D Array: ",arr1d.nbytes)
print("Memory occupied by 2D Array: ",arr2d.nbytes)
print("Memory occupied by 3D Array: ",arr3d.nbytes)

Memory occupied by 1D Array:  32
Memory occupied by 2D Array:  48
Memory occupied by 3D Array:  96


Another fun fact:\
nbytes = size * itemsize

In [38]:
print("Size of our 3D Array: ",arr3d.size)
print("Itemsize of our 3D Array: ",arr3d.itemsize)
print("Memory occupied by entire 3D Array: ",arr3d.nbytes)

Size of our 3D Array:  12
Itemsize of our 3D Array:  8
Memory occupied by entire 3D Array:  96


**Tips**\
How many dimensions? → ndim\
How many rows/columns? → shape\
How many total values? → size\
What type of values? → dtype\
Memory per value? → itemsize\
Total memory? → nbytes