# <center>Advanced NumPy Toolkit (Data Cleaning & Logic)</center>

**In real datasets, the problem is not:**\
How do i calculate means?\
**The problem is often:**\
What do I do with missing values?\
How do I filter bad data?\
How do I extract only meaningful rows?\
How do I handle conditions efficiently?\
**This toolkit solves these very problems**

**1) Boolean Masking(Conditional Selection)**

In [4]:
import numpy as np
data = np.array([10,25,30,45,50])
print(f"Boolean Mask: {data>30}")

Boolean Mask: [False False False  True  True]


Boolean Mask can also be used to print those elements of an array where condition is satisfied.

In [5]:
data[data>30]

array([45, 50])

**2) Multiple Conditions**\
Always keep each condition within parentheses\
Use '&' not "and"\
Use '|' not "or"\
Use '~' not "not"

**a. AND:**

In [6]:
data[(data>20) & (data<50)]

array([25, 30, 45])

**b. OR:**

In [7]:
data[(data>20) | (data<50)]

array([10, 25, 30, 45, 50])

**c. NOT:**

In [8]:
data[~(data>30)]

array([10, 25, 30])

**3) np.where() (Decision Engine)**\
It's like if-else for arrays

In [10]:
ages = np.array([17,14,21,12,23,62])
np.where(ages>=18,"Adult","child")

array(['child', 'child', 'Adult', 'child', 'Adult', 'Adult'], dtype='<U5')

**4) np.select() (Multi Condition Logic)**\
useful when there are multiple conditions

In [12]:
conditions=[
    ages<18,
    (ages>=18) & (ages<=60),
    ages>60
]
choices = ["child","adult","retired"]
np.select(conditions,choices,default="")

array(['child', 'child', 'adult', 'child', 'adult', 'retired'],
      dtype='<U7')

**5) Handling Missing Data (NaN)**

a. Create missing values:

In [13]:
data = np.array([10,np.nan,30,np.nan,50])

b. Detect missing values:

In [14]:
np.isnan(data)

array([False,  True, False,  True, False])

c. Remove missing values:

In [15]:
data[~np.isnan(data)]

array([10., 30., 50.])

**6) NaN safe statistics:**\
Normal functions break with NaN\
np.mean(data)  #may return NaN\
NaN safe methods are used as follows:

In [20]:
print(np.nanmean(data))
print(np.nanmedian(data))
print(np.nanstd(data))

30.0
30.0
16.32993161855452


**7) np.clip() (Value Control)**\
Used for limiting values

In [21]:
data = np.array([10,20,30,40,50])
np.clip(data,20,40)

array([20, 20, 30, 40, 40])

**8) argmax & argmin**\
argmax: index of max value in the array\
argmin: index of min value in the array

In [24]:
data = np.array([10,50,30])
print(np.argmax(data))
print(np.argmin(data))

1
0


**9) argsort()**\
sort but return indices only.

In [25]:
data = np.array([40,10,30])
np.argsort(data)

array([1, 2, 0])

**10) np.unique()**\
Find distinct values

In [29]:
data = np.array([1,1,2,2,3,3,3])
np.unique(data)

array([1, 2, 3])

With counts:

In [30]:
np.unique(data,return_counts=True)

(array([1, 2, 3]), array([2, 2, 3]))

**11) Logical Reductions(any & all)**

**a. any():** True if any value matches condition\
**b. all():** True if all values match condition

In [33]:
data = np.array([10,20,30,40,50])
print(np.any(data>40))
print(np.all(data>0))

True
True


**REAL INDUSTRY EXAMPLE**(Everything Combined)

In [34]:
data = np.array([10,25,np.nan,45,60,np.nan])

**Step1**: Clean data

In [35]:
clean = data[~np.isnan(data)]

**Step2**: Clip Extreme Values

In [36]:
clean = np.clip(clean,20,50)

**Step3**: Label data

In [37]:
np.where(clean>40,"High","Low")

array(['Low', 'Low', 'High', 'High'], dtype='<U4')

**Step4**: NaN Safe Statistics

In [38]:
np.nanmean(clean)

np.float64(35.0)

In [39]:
np.nanstd(clean)

np.float64(12.747548783981962)