**<center>Vectorization Mathematics</center>**\
Applying an operation to an entire array at once

**1. Vectorized Arithmetic Operations**\
Let's create array to work on:

In [1]:
import numpy as np
arr = np.array([10,20,30,40])

a) Addition (+)

In [3]:
arr + 5

array([15, 25, 35, 45])

b) Subtraction (-)

In [4]:
arr - 5

array([ 5, 15, 25, 35])

c) Multiplication (*)

In [6]:
arr * 2

array([20, 40, 60, 80])

d) Division (/)

In [8]:
arr / 10

array([1., 2., 3., 4.])

e) Exponent (**)

In [9]:
arr ** 2

array([ 100,  400,  900, 1600])

f) Floor Division (//)

In [11]:
arr // 3

array([ 3,  6, 10, 13])

g) Modulus (%)

In [14]:
arr % 3

array([1, 2, 0, 1])

**2. Inter Array Operations**\
Lets create 2 arrays to work on

In [2]:
a = np.array([1,2,3])
b = np.array([4,5,6])

a) Addition

In [5]:
a + b

array([5, 7, 9])

b)Subtraction

In [6]:
a-b

array([-3, -3, -3])

c) Multiplication

In [8]:
a*b

array([ 4, 10, 18])

d) Division

In [10]:
a / b

array([0.25, 0.4 , 0.5 ])

**3. Comparison Operations**

In [11]:
ages = np.array([12,18,25,30,15])

a) Greater Than

In [13]:
ages > 18

array([False, False,  True,  True, False])

b) Less Than

In [14]:
ages < 18

array([ True, False, False, False,  True])

c) Equal To

In [15]:
ages == 25

array([False, False,  True, False, False])

**4. Universal Functions (ufuncs)**

a) Square Root

In [19]:
arr = np.array([1,4,9,16])
np.sqrt(arr)

array([1., 2., 3., 4.])

b) Absolute Value

In [22]:
arr = np.array([-5,-2,4,-1])
np.abs(arr)

array([5, 2, 4, 1])

c) Exponential e

In [30]:
np.exp([1,2,3])

array([ 2.71828183,  7.3890561 , 20.08553692])

d) Natural Logarithm

In [37]:
print(np.log([1]))
print(np.log([np.e]))
print(np.log([np.e**2]))

[0.]
[1.]
[2.]


**5. Trigonometric Functions**

In [43]:
print(np.sin(np.pi/6))
print(np.cos(np.pi/6))
print(np.tan(np.pi/3))

0.49999999999999994
0.8660254037844387
1.7320508075688767


**6. Aggregation Functions**\
Let's create array first

In [44]:
sales = np.array([100,200,300,400])

a) Sum

In [46]:
np.sum(sales)

np.int64(1000)

b) Mean

In [48]:
np.mean(sales)

np.float64(250.0)

c) Min

In [49]:
np.min(sales)

np.int64(100)

d) Max

In [50]:
np.max(sales)

np.int64(400)

e) Standard Deviation

In [52]:
np.std(sales)

np.float64(111.80339887498948)

f) Variance

In [54]:
np.var(sales)

np.float64(12500.0)

**7. Axis wise operations**

In [55]:
sales = np.array([
    [100,200,300],
    [400,500,600],
    [700,800,900]
])

In [56]:
print("Normal Sum: ",np.sum(sales))

Normal Sum:  4500


In [57]:
print("Column Wise Sum: ",np.sum(sales,axis=0))

Column Wise Sum:  [1200 1500 1800]


In [58]:
print("Row Wise Sum: ",np.sum(sales,axis=1))

Row Wise Sum:  [ 600 1500 2400]
