# <center>Retail Customer Intelligence Analysis
You have joined a retail analytics team as a Junior Data Scientist.\
The company has provided a customer dataset and wants you to prepare a report for management.\
You are only allowed to use:\
NumPy\
No Pandas.\
No Scikit-learn.\
No ChatGPT-generated code.
#### Dataset:

In [45]:
import numpy as np

data = np.array([
[1,22,50000,45,1],
[2,25,70000,60,2],
[3,30,90000,80,5],
[4,21,45000,40,1],
[5,35,120000,90,8],
[6,42,150000,95,10],
[7,28,np.nan,70,3],
[8,31,85000,75,4],
[9,29,78000,65,3],
[10,60,250000,20,20],
[11,24,52000,55,2],
[12,27,68000,62,3]
], dtype=float)

**Columns:**\
CustomerID\
Age\
Salary\
SpendingScore\
YearsAsCustomer

**Your Mission**\
Management wants a complete customer intelligence report.\
Your task is divided into stages.\
Do NOT skip stages.\
Think of each stage as a deliverable requested by your manager.

### Stage 1 — Dataset Understanding
Before analyzing anything, understand the dataset.\
**Questions:**\
How many customers are present?\
How many features exist?\
What is the shape of the dataset?\
Separate every column into its own NumPy array.\
Verify the datatype of the dataset.\
**Deliverable:**\
Dataset Overview Report

In [46]:
rows,columns = data.shape
print(f"Number of customers: {rows}")
print(f"Number of features: {columns}")
print(f"Shape of the dataset: {data.shape}")
cust_id = data[:,0]
age = data[:,1]
salary = data[:,2]
spending_score = data[:,3]
years = data[:,4]
print(f"Customer IDs : {cust_id}")
print(f"Ages: {age}")
print(f"Salaries: {salary}")
print(f"Spending Score: {spending_score}")
print(f"Years as Customer: {years}")
print(f"Datatype of the dataset: {data.dtype}")

Number of customers: 12
Number of features: 5
Shape of the dataset: (12, 5)
Customer IDs : [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12.]
Ages: [22. 25. 30. 21. 35. 42. 28. 31. 29. 60. 24. 27.]
Salaries: [ 50000.  70000.  90000.  45000. 120000. 150000.     nan  85000.  78000.
 250000.  52000.  68000.]
Spending Score: [45. 60. 80. 40. 90. 95. 70. 75. 65. 20. 55. 62.]
Years as Customer: [ 1.  2.  5.  1.  8. 10.  3.  4.  3. 20.  2.  3.]
Datatype of the dataset: float64


### Stage 2 — Data Quality Assessment
Management is worried about bad data.\
**Investigate:**\
Are there any missing values?\
How many missing values exist?\
Which row(s) contain missing values?\
Which column(s) contain missing values?\
What percentage of salary values are missing?\
**Deliverable:**\
Data Quality Report

In [47]:
print(f"Number of missing values: {np.sum(np.isnan(data))}")
missing = np.where(np.isnan(data))
print(f"Row(s) containing missing values: {missing[0]+1}")
print(f"Column(s) containing missing values: {missing[1]+1}")
print(f"Percentage of missing values: {((np.sum(np.isnan(data))/data.size)*100)} %")

Number of missing values: 1
Row(s) containing missing values: [7]
Column(s) containing missing values: [3]
Percentage of missing values: 1.6666666666666667 %


### Stage 3 — Missing Value Treatment
The analytics team wants the dataset cleaned.\
**Tasks:**\
Decide how to handle the missing salary value.\
Replace the missing salary value appropriately.\
Verify no missing values remain.\
**Deliverable:**\
Clean Dataset

In [48]:
data[np.where(np.isnan(data))] = np.nanmedian(data[:,2])
np.set_printoptions(suppress=True)
print(f"Updated data:\n{data}")
missing = np.where(np.isnan(data))
print(f"Missing values now: {missing}")

Updated data:
[[     1.     22.  50000.     45.      1.]
 [     2.     25.  70000.     60.      2.]
 [     3.     30.  90000.     80.      5.]
 [     4.     21.  45000.     40.      1.]
 [     5.     35. 120000.     90.      8.]
 [     6.     42. 150000.     95.     10.]
 [     7.     28.  78000.     70.      3.]
 [     8.     31.  85000.     75.      4.]
 [     9.     29.  78000.     65.      3.]
 [    10.     60. 250000.     20.     20.]
 [    11.     24.  52000.     55.      2.]
 [    12.     27.  68000.     62.      3.]]
Missing values now: (array([], dtype=int64), array([], dtype=int64))


### Stage 4 — Descriptive Analytics
Management wants to know what a typical customer looks like.\
**For each feature:**\
Age\
Salary\
SpendingScore\
YearsAsCustomer\
**Calculate:**\
Mean\
Median\
Standard deviation\
Minimum\
Maximum\
**Deliverable:**\
Customer Profile Summary

In [49]:
print(f"Mean of Ages: {np.mean(data[:,1])}")
print(f"Mean of Salary: {np.mean(data[:,2])}")
print(f"Mean of Spending Score: {np.mean(data[:,3])}")
print(f"Mean of Years as Customers: {np.mean(data[:,4])}")

Mean of Ages: 31.166666666666668
Mean of Salary: 94666.66666666667
Mean of Spending Score: 63.083333333333336
Mean of Years as Customers: 5.166666666666667


In [38]:
print(f"Median of Ages: {np.median(data[:,1])}")
print(f"Median of Salary: {np.median(data[:,2])}")
print(f"Median of Spending Score: {np.median(data[:,3])}")
print(f"Median of Years as Customers: {np.median(data[:,4])}")

Median of Ages: 28.5
Median of Salary: 78000.0
Median of Spending Score: 63.5
Median of Years as Customers: 3.0


In [39]:
print(f"Standard Deviation of Ages: {np.std(data[:,1])}")
print(f"Standard Deviation of Salary: {np.std(data[:,2])}")
print(f"Standard Deviation of Spending Score: {np.std(data[:,3])}")
print(f"Standard Deviation of Years as Customers: {np.std(data[:,4])}")

Standard Deviation of Ages: 10.302372973683726
Standard Deviation of Salary: 54851.82059168339
Standard Deviation of Spending Score: 20.44284036581566
Standard Deviation of Years as Customers: 5.177408189003022


In [40]:
print(f"Minimum Age: {data[:,1].min()}")
print(f"Minimum Salary: {data[:,2].min()}")
print(f"Minimum Spending Score: {data[:,3].min()}")
print(f"Minimum Years as Customers: {data[:,4].min()}")

Minimum Age: 21.0
Minimum Salary: 45000.0
Minimum Spending Score: 20.0
Minimum Years as Customers: 1.0


In [41]:
print(f"Maximum Age: {data[:,1].max()}")
print(f"Maximum Salary: {data[:,2].max()}")
print(f"Maximum Spending Score: {data[:,3].max()}")
print(f"Maximum Years as Customers: {data[:,4].max()}")

Maximum Age: 60.0
Maximum Salary: 250000.0
Maximum Spending Score: 95.0
Maximum Years as Customers: 20.0


### Stage 5 — Customer Ranking
**Management wants to identify:**\
Customer with highest salary\
Customer with lowest salary\
Customer with highest spending score\
Customer with lowest spending score\
**Deliverable:**\
Top and Bottom Customers Report

In [49]:
print(f"Customer with highest salary: {data[data[:,2]==data[:,2].max()]}")

Customer with highest salary: [[    10.     60. 250000.     20.     20.]]


In [50]:
print(f"Customer with lowest salary: {data[data[:,2]==data[:,2].min()]}")

Customer with lowest salary: [[    4.    21. 45000.    40.     1.]]


In [51]:
print(f"Customer with highest spending score: {data[data[:,3]==data[:,3].max()]}")

Customer with highest spending score: [[     6.     42. 150000.     95.     10.]]


In [52]:
print(f"Customer with lowest spending score: {data[data[:,3]==data[:,3].min()]}")

Customer with lowest spending score: [[    10.     60. 250000.     20.     20.]]


### Stage 6 — Outlier Investigation
Finance suspects unusual salaries.\
**Tasks:**\
Detect salary outliers using the IQR method.\
List all detected outlier salaries.\
Identify the customer IDs associated with those outliers.\
Explain whether these customers should be investigated further.\
**Deliverable:**\
Outlier Analysis Report

In [50]:
q1 = np.percentile(data[:,2],25)
q3 = np.percentile(data[:,2],75)
iqr = q3-q1
lower = q1 - 1.5 * iqr
upper = q3 + 1.5 * iqr
outliers = data[(data[:,2]<lower) | (data[:,2]>upper)]
print(f"Outliers: \n{outliers}")
index = np.where((data[:,2]<lower) | (data[:,2]>upper))
print(f"Customer IDs of outliers: \n{data[index,0]}")

Outliers: 
[[     6.     42. 150000.     95.     10.]
 [    10.     60. 250000.     20.     20.]]
Customer IDs of outliers: 
[[ 6. 10.]]


### Stage 7 — Customer Segmentation
Marketing wants customer categories.\
**Create:**\
Low Income\
Medium Income\
High Income\
You must decide reasonable salary ranges.\
**Tasks:**\
Assign every customer to a segment.\
Count customers in each segment.\
Calculate the percentage in each segment.\
**Deliverable:**\
Income Segmentation Report

In [51]:
salary = data[:,2]
conditions = (
    salary<=60000,
    (salary>60000) & (salary<=100000),
    salary>100000
)
choices = ["Low income", "Medium income", "High income"]
segments = np.select(conditions, choices, default="")
data_segments = np.column_stack((data,segments))
low = np.array(np.where(data_segments[:,5] == "Low income"))
medium = np.array(np.where(data_segments[:,5] == "Medium income"))
high = np.array(np.where(data_segments[:,5] == "High income"))
print(f"Number of low income customers: {low.size} equivalent to {(low.size/(low.size+medium.size+high.size))*100}%")
print(f"Number of medium income customers: {medium.size} equivalent to {(medium.size/(low.size+medium.size+high.size))*100}%")
print(f"Number of high income customers: {high.size} equivalent to {(high.size/(low.size+medium.size+high.size))*100}%")

Number of low income customers: 3 equivalent to 25.0%
Number of medium income customers: 6 equivalent to 50.0%
Number of high income customers: 3 equivalent to 25.0%


### Stage 8 — High-Value Customer Detection
**Management defines a High-Value Customer as:**\
Salary above average\
AND\
Spending Score above average\
**Tasks:**\
Find all high-value customers.\
Count them.\
Determine what percentage of customers are high-value.\
**Deliverable:**\
VIP Customer Report

In [52]:
vip = data[(data[:,2]>np.mean(data[:,2])) & (data[:,3]>np.mean(data[:,3]))]
print(f"VIP Customer Details: \n{vip}")
rows,columns=vip.shape
print(f"Number of VIP Customers: {rows}")
rows_of_data,columns_of_data = data.shape
print(f"Percentage of VIP Customers: {(rows/rows_of_data)*100} %")

VIP Customer Details: 
[[     5.     35. 120000.     90.      8.]
 [     6.     42. 150000.     95.     10.]]
Number of VIP Customers: 2
Percentage of VIP Customers: 16.666666666666664 %


### Stage 9 — Correlation Analysis
Management wants to understand customer behavior.\
**Analyze relationships among:**\
Age\
Salary\
SpendingScore\
YearsAsCustomer\
**Tasks:**\
Generate a correlation matrix.\
Identify strongest positive correlation.\
Identify strongest negative correlation.\
Identify weakest correlation.\
Interpret each finding in business terms.\
**Deliverable:**\
Relationship Analysis Report

In [53]:
matrix = np.corrcoef(data,rowvar=False)
print(f"Correlation Matrix: \n{matrix}")
corr_no_diag = matrix.copy()
np.fill_diagonal(corr_no_diag, -np.inf) # replace diagonal with negative infinity so the max value is not 1
max_corr = np.max(corr_no_diag)
print(f"Maximum Positive Correlation:{max_corr}")
np.fill_diagonal(corr_no_diag, np.inf)
min_corr = np.min(corr_no_diag)
print(f"Strongest Negative Correlation: {min_corr}")
weakest = np.min(np.abs(corr_no_diag))
print(f"Weakest correlation: {weakest}")

Correlation Matrix: 
[[ 1.          0.31632816  0.25173659 -0.13166641  0.2750939 ]
 [ 0.31632816  1.          0.99608032 -0.14211381  0.99155034]
 [ 0.25173659  0.99608032  1.         -0.16213429  0.99524147]
 [-0.13166641 -0.14211381 -0.16213429  1.         -0.18515731]
 [ 0.2750939   0.99155034  0.99524147 -0.18515731  1.        ]]
Maximum Positive Correlation:0.99608032243759
Strongest Negative Correlation: -0.18515731471574315
Weakest correlation: 0.13166640817871847


### Stage 10 — Feature Engineering
Create at least three new features.\
**Examples (you may invent your own):**\
Customer Value Score\
Loyalty Score\
Spending Efficiency\
**Tasks:**\
Create three engineered features.\
Explain why each feature may be useful.\
Add them to a new feature matrix.\
**Deliverable:**\
Enhanced Dataset

In [57]:
age = data[:,1]
salary = data[:,2]
spending = data[:,3]
years = data[:,4]
value_score = salary * spending
loyalty_score = years * spending
spending_ratio = spending / salary
X = np.column_stack((
    age,
    salary,
    spending,
    years,
    value_score,
    loyalty_score,
    spending_ratio
))
print("Enhanced Feature Matrix:")
print(X)
print("\nShape:", X.shape)

Enhanced Feature Matrix:
[[      22.            50000.               45.                1.
   2250000.               45.                0.0009    ]
 [      25.            70000.               60.                2.
   4200000.              120.                0.00085714]
 [      30.            90000.               80.                5.
   7200000.              400.                0.00088889]
 [      21.            45000.               40.                1.
   1800000.               40.                0.00088889]
 [      35.           120000.               90.                8.
  10800000.              720.                0.00075   ]
 [      42.           150000.               95.               10.
  14250000.              950.                0.00063333]
 [      28.            78000.               70.                3.
   5460000.              210.                0.00089744]
 [      31.            85000.               75.                4.
   6375000.              300.                0.0

### Stage 11 — Normalization and Standardization
Data is being prepared for Machine Learning.\
**Tasks:**\
Normalize all numerical features.\
Standardize all numerical features.\
Verify the normalization results.\
Verify the standardization results.\
**Deliverable:**\
ML-Ready Features

In [54]:
normalized_age = (age-age.min())/(age.max()-age.min())
normalized_salary = (salary-salary.min())/(salary.max()-salary.min())
normalized_spending_score = (spending_score-spending_score.min())/(spending_score.max()-spending_score.min())
normalized_years = (years-years.min())/(years.max()-years.min())
print("After Normalization:")
print(f" Minimum value in ages: {normalized_age.min()} and Maximum value in ages: {normalized_age.max()}")
print(f" Minimum value in salary: {normalized_salary.min()} and Maximum value in salary: {normalized_salary.max()}")
print(f" Minimum value in spending score: {normalized_spending_score.min()} and Maximum value in spending score: {normalized_spending_score.max()}")
print(f" Minimum value in years as customers: {normalized_years.min()} and Maximum value in years as customers: {normalized_years.max()}")

After Normalization:
 Minimum value in ages: 0.0 and Maximum value in ages: 1.0
 Minimum value in salary: 0.0 and Maximum value in salary: 1.0
 Minimum value in spending score: 0.0 and Maximum value in spending score: 1.0
 Minimum value in years as customers: 0.0 and Maximum value in years as customers: 1.0


In [55]:
standardized_age = (age-np.mean(age))/np.std(age)
standardized_salary = (salary-np.mean(salary))/np.std(salary)
standardized_spending_score =(spending_score-np.mean(spending_score))/np.std(spending_score)
standardized_years = (years-np.mean(years))/np.std(years)
print("After Standardization:")
print(f" Mean of ages: {np.mean(standardized_age)} and Standard Deviation of ages: {np.std(standardized_age)}")
print(f" Mean of salary: {np.mean(standardized_salary)} and  Standard Deviation of salary: {np.std(standardized_salary)}")
print(f" Mean of spending score: {np.mean(standardized_spending_score)} and Standard Deviation of spending score: {np.std(standardized_spending_score)}")
print(f" Mean of years as customer: {np.mean(standardized_years)} and Standard Deviation of years as customers: {np.std(standardized_years)}")

After Standardization:
 Mean of ages: -1.4802973661668753e-16 and Standard Deviation of ages: 1.0
 Mean of salary: -9.251858538542972e-17 and  Standard Deviation of salary: 0.9999999999999999
 Mean of spending score: -9.656627349604226e-17 and Standard Deviation of spending score: 1.0000000000000002
 Mean of years as customer: -5.088522196198634e-17 and Standard Deviation of years as customers: 1.0


### Stage 12 — Train/Test Split
Prepare data for a future ML model.\
**Tasks:**\
Create a target variable.\
**Example:**\
Premium Customer\
or\
High Spender\
**Build:**\
X\
y\
Shuffle data.\
**Split into:**\
80% Train\
20% Test\
Verify shapes.\
**Deliverable:**\
Training Dataset\
Testing Dataset

In [56]:
x_std = np.column_stack((standardized_age,standardized_salary,standardized_spending_score,standardized_years))
import numpy as np
y = (spending_score > 70).astype(int)
indices = np.random.permutation(len(x_std))
split = int(0.8 * len(x_std))
train_idx = indices[:split]
test_idx = indices[split:]

X_train = x_std[train_idx]
X_test = x_std[test_idx]

y_train = y[train_idx]
y_test = y[test_idx]

print("X_train:", X_train.shape)
print("X_test :", X_test.shape)
print("y_train:", y_train.shape)
print("y_test :", y_test.shape)

X_train: (9, 4)
X_test : (3, 4)
y_train: (9,)
y_test : (3,)


### Stage 13 — Executive Summary
**Dataset Overview**\
Total Customers: 12\
Original Features: 4 business features\
Engineered Features Added: 3\
Final Feature Count: 7\
**Data Quality**\
Missing values detected in Salary column.\
One missing salary value existed.\
Missing value replaced using median salary.\
Dataset contains no missing values after cleaning.\
**Customer Profile**\
The customer base contains a mixture of:\
Young customers\
Mid-career customers\
High-income customers\
Long-term loyal customers\
The average salary is elevated by a very high-income customer.\
**Outlier Analysis**\
IQR analysis identifies:\
250,000 salary\
as a likely outlier.\
**Possible explanations:**\
VIP customer\
Executive-level customer\
Data entry issue\
Should be investigated.\
**Customer Segmentation**\
**Customers can be grouped into:**\
Low Income\
Medium Income\
High Income\
The company serves a mixed-income customer base with a smaller premium segment.\
VIP Customers\
**Definition:**\
Salary above average\
AND\
Spending above average\
These customers represent the most valuable segment and should be prioritized for retention campaigns.\
**Correlation Findings**\
Strongest positive relationships indicate:\
Higher salaries tend to be associated with higher spending.\
Longer customer tenure may also contribute to customer value.\
**Feature Engineering**\
**Created:**\
Value Score\
Loyalty Score\
Spending Efficiency\
These provide richer information than raw salary and spending values alone.\
**Machine Learning Readiness**\
Completed:\
Missing value handling\
Feature Engineering\
Normalization\
Standardization\
Target creation\
Train-test split\
**Result:**\
Dataset is ready for machine learning experimentation.