# <center> Real Data Science Workflows </center>

**Workflow 1: Customer Analytics**

In [2]:
import numpy as np
customers = np.array([
    [22,50000,2000],
    [25,70000,3000],
    [30,90000,5000],
    [21,45000,1500],
    [35,120000,7000]
])

Step 1: Understand Shape

In [3]:
customers.shape

(5, 3)

This means 5 customers and 3 features

Step 2: Separate Features

In [13]:
age = customers[:,0]
salary = customers[:,1]
spending = customers[:,2]
print(f"Ages: {age}")
print(f"Salary: {salary}")
print(f"Spending: {spending}")

Ages: [22 25 30 21 35]
Salary: [ 50000  70000  90000  45000 120000]
Spending: [2000 3000 5000 1500 7000]


Step 3: Basic Statistics

In [11]:
average_customer = np.array([np.mean(age),np.mean(salary),np.mean(spending)])
print(f"An Average Customer: {average_customer}")

An Average Customer: [2.66e+01 7.50e+04 3.70e+03]


Step 4: Spread

In [12]:
print(f"Spread in the salary: {np.std(salary)}")

Spread in the salary: 27568.097504180445


High Standard Deviation --> Customers differ greatly\
Low Standard Deviation --> Customers are similar

Step 5: High Value Customers\
Business question:\
Which customers spend more than average?

In [16]:
customers[spending>np.mean(spending)]

array([[    30,  90000,   5000],
       [    35, 120000,   7000]])

This is a classic segmentation task.

**Workflow 2: Outlier Detection**

In [18]:
salary = np.array([45000,50000,52000,55000,60000,250000])

Step 1: Compute Quartiles

In [19]:
q1 = np.percentile(salary,25)
q3 = np.percentile(salary,75)

Step 2: Interquartile Range

In [21]:
iqr = q3 - q1

Step 3: Defining Limits

In [22]:
lower = q1 - 1.5 * iqr
upper = q3 + 1.5 * iqr

Step 4: Detect Outliers

In [23]:
salary[(salary<lower)|(salary>upper)]

array([250000])

**Workflow 3: Correlation Analysis**

In [29]:
salary = np.array([30000,50000,70000,90000])
spending = np.array([1000,2500,4000,6000])

Correlation:

In [30]:
corr = np.corrcoef(salary,spending)
print(f"Correlation Matrix:\n{corr}")

Correlation Matrix:
[[1.         0.99725651]
 [0.99725651 1.        ]]


Extract:

In [31]:
corr[0,1]

np.float64(0.997256510605574)

Interpretation:\
Strong Positive Relationship\
High Income Customers Spend more.

**Workflow 4: Customer Segmentation**

In [33]:
salary = np.array([30000,50000,70000,100000])

Business wants:\
Low Income\
Medium Income\
High Income

In [36]:
conditions = [
    salary<40000,
    (salary>=40000) & (salary<80000),
    salary>80000
]
choices=["low","medium","high"]
np.select(conditions,choices,"")

array(['low', 'medium', 'medium', 'high'], dtype='<U6')

This is customer segmentation

**Workflow 5: Missing Data Investigation**\
Real Datasets are messy

In [37]:
salary = np.array([50000,np.nan,70000,np.nan,90000])

How many missing?

In [38]:
np.sum(np.isnan(salary))

np.int64(2)

What percent of values are missing?

In [39]:
(np.sum(np.isnan(salary))/salary.size)*100

np.float64(40.0)

Mean ignoring NaNs

In [40]:
np.nanmean(salary)

np.float64(70000.0)

**Workflow 6: Product Performance Analysis**

In [41]:
sales = np.array([1200,500,2000,1500,3000])
products = np.array(["A","B","C","D","E"])

Best Product: 

In [42]:
idx = np.argmax(sales)
products[idx]

np.str_('E')

Worst Product:

In [43]:
idx = np.argmin(sales)
products[idx]

np.str_('B')

Ranking Products:

In [45]:
products[np.argsort(sales)]

array(['B', 'A', 'D', 'C', 'E'], dtype='<U1')

**Business usage:**\
Top sellers\
Bottom sellers\
Inventory planning

**Workflow 7: Survey Analytics**

In [46]:
ratings = np.array([5,4,4,5,3,2,5,4,5,3])

Average Satisfaction:

In [47]:
np.mean(ratings)

np.float64(4.0)

Distribution:

In [48]:
np.unique(ratings, return_counts = True)

(array([2, 3, 4, 5]), array([1, 2, 3, 4]))

Dissatisfied Customers:

In [49]:
np.sum(ratings <= 2)

np.int64(1)

**Workflow 8: Probability-Based Business Analysis**

In [50]:
salary = np.array([30000,40000,50000,80000,100000])

Probability customer earns above 60k?

In [51]:
np.mean(salary>60000)

np.float64(0.4)

Interpretation:\
40% of customers

**Workflow 9: Feature Engineering**\
This is where new features are created\
**Suppose:**\
salary\
spending\
exist.\
**Create:**
spending_ratio = spending/salary\
This new feature may be more informative than either original feature.\
Real data science does this constantly.

**Workflow 10: Building a Data Science Summary Report**
For every feature:\
**Calculate:**\
mean\
median\
std\
min\
max\
quartiles\
missing values\
**Then answer:**\
What is normal?\
What is unusual?\
What relationships exist?\
What should be investigated?\
\
This is called:\
**Exploratory Data Analysis (EDA)**\
and it is one of the most important skills in Data Science.