**<center>Array Manipulation</center>**

**1. Reshape**\
Reshaping changes only "shape" , it does not affect the "data", "size" or "values".

In [2]:
import numpy as np
arr = np.array([1,2,3,4,5,6])
print("Array: ",arr)
print("Original Shape of the array: ", arr.shape)

Array:  [1 2 3 4 5 6]
Original Shape of the array:  (6,)


Example 1: Lets reshape into 2 Rows and 3 Columns

In [3]:
print(arr.reshape(2,3))

[[1 2 3]
 [4 5 6]]


Example 2: Lets reshape into 3 Rows and 2 Columns

In [4]:
print(arr.reshape(3,2))

[[1 2]
 [3 4]
 [5 6]]


You can always declare one dimension and the NumPy automatically calculates the other based on size of array.\
For instance: We can say reshape an array of 6 elements to 2 rows, unknown columns, and NumPy automatically calculates there will be 3 columns as demonstrated below.\
Remember: The unknown dimension is written as -1.

Example 3: Lets reshape into 3 Rows

In [5]:
print(arr.reshape(3,-1))

[[1 2]
 [3 4]
 [5 6]]


Example 4: Lets reshape into 3 Columns

In [6]:
print(arr.reshape(-1,3))

[[1 2 3]
 [4 5 6]]


\
\
**2. Flatten**\
Reshape increases dimensions, flatten does the opposite

In [8]:
arr = np.array([
    [1,2,3],
    [4,5,6]
])
print("Array: \n",arr)
print("Current Shape: ",arr.shape)

Array: 
 [[1 2 3]
 [4 5 6]]
Current Shape:  (2, 3)


Example 1: Lets flatten

In [12]:
print(arr.flatten())

[1 2 3 4 5 6]


Another method is ravel(), which usually creates a view of the array

In [10]:
print(arr.ravel())

[1 2 3 4 5 6]


\
\
**3. Transposing Arrays**\
Swapping between rows and columns

In [14]:
arr = np.array([
    [1,2,3,4],
    [5,6,7,8]
])
print("Array: \n",arr)
print("Current Shape: ",arr.shape)

Array: 
 [[1 2 3 4]
 [5 6 7 8]]
Current Shape:  (2, 4)


Example 1: Let's take the transpose of this array

In [18]:
transpose = arr.T
print("Transpose: \n",transpose)
print("Shape now: ",transpose.shape)

Transpose: 
 [[1 5]
 [2 6]
 [3 7]
 [4 8]]
Shape now:  (4, 2)


\
\
**4. Adding Dimensions**\
Adding row vector or column vector

In [20]:
arr = np.array([10,20,30])
print("Array: ",arr)
print("Original Shape: ", arr.shape)

Array:  [10 20 30]
Original Shape:  (3,)


Let's add row vector

In [21]:
row_vector = arr[np.newaxis, :]
print("Array now: ",row_vector)
print("Shape now: ",row_vector.shape)

Array now:  [[10 20 30]]
Shape now:  (1, 3)


Let's add column vector

In [23]:
col_vector = arr[:,np.newaxis]
print("Array now: \n",col_vector)
print("Shape now: ",col_vector.shape)

Array now: 
 [[10]
 [20]
 [30]]
Shape now:  (3, 1)


\
\
**5. Combining Arrays**\
various methods to do it as discussed below:

a) Concatenate(): appends

In [25]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(np.concatenate((a,b)))

[1 2 3 4 5 6]


b) vstack(): vertical stacking

In [26]:
print(np.vstack((a,b)))

[[1 2 3]
 [4 5 6]]


c) hstack(): horizontal stacking

In [28]:
print(np.hstack((a,b)))

[1 2 3 4 5 6]


d) stack(): create new dimensions

In [30]:
print(np.stack((a,b)))

[[1 2 3]
 [4 5 6]]


\
\
**6. Splitting Arrays**\
Opposite of Stacking

a) split(): opposite of stacking

In [34]:
arr = np.array([1,2,3,4,5,6])
print(np.split(arr,2))

[array([1, 2, 3]), array([4, 5, 6])]


b) hsplit(): split columns

In [35]:
arr = np.array([
    [1,2,3,4],
    [5,6,7,8]
])
print(np.hsplit(arr,2))

[array([[1, 2],
       [5, 6]]), array([[3, 4],
       [7, 8]])]


c) vsplit(): split rows

In [36]:
print(np.vsplit(arr,2))

[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]])]


\
\
\
**<center>Practice Challenge Questions</center>**\
**Challenge 1**\
arr = np.arange(24)\
Convert it into:\
4 rows\
6 columns

In [38]:
arr = np.arange(24)
print(arr.reshape(4,6))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


\
**Challenge 2**\
arr = np.array([\
    [1,2,3],\
    [4,5,6]\
])\
Create:\
3 rows\
2 columns\
without manually typing values.

In [40]:
arr = np.array([
[1,2,3],
[4,5,6]
])
print(arr.reshape(3,2))

[[1 2]
 [3 4]
 [5 6]]


\
**Challenge 3**\
Combine:\
jan = np.array([100,120,130])\
feb = np.array([140,150,160])\
mar = np.array([170,180,190])\
into a single 3×3 matrix where each row represents a month.

In [42]:
jan = np.array([100,120,130])
feb = np.array([140,150,160])
mar = np.array([170,180,190])
print(np.vstack((jan,feb,mar)))

[[100 120 130]
 [140 150 160]
 [170 180 190]]


\
**Challenge 4**\
Convert:\
[22,25,30,21]\
into a column vector suitable for machine learning.

In [44]:
arr = np.array([22,25,30,21])
print(arr[:,np.newaxis])

[[22]
 [25]
 [30]
 [21]]


Alternate Method:

In [45]:
print(arr.reshape(-1,1))

[[22]
 [25]
 [30]
 [21]]


\
**Challenge 5**\
Given:\
sales = np.arange(1,13)\
Create a dataset representing:\
4 quarters\
3 months each\
using reshape only.

In [47]:
sales = np.arange(1,13)
print(sales.reshape(4,3))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
