**<center>Level 1: Junior Data Analyst (Easy)</center>**

\
**Problem 1: Daily Website Visitors**\
A startup stores daily visitor counts.\
visitors = np.array([120, 145, 132, 167, 189, 210, 195])\
**Tasks:**\
Get the first day's visitors.\
Get the last day's visitors.\
Get visitors for the first 3 days.\
Get visitors for the weekend (last 2 days).

In [1]:
import numpy as np
visitors = np.array([120,145,132,167,189,210,195])
print("First day's visitors: ", visitors[0])
print("Last day's visitos: ", visitors[-1])
print("Visitors for the first three days: ", visitors[:3])
print("Visitors for the weekend: ", visitors[-2:])

First day's visitors:  120
Last day's visitos:  195
Visitors for the first three days:  [120 145 132]
Visitors for the weekend:  [210 195]


\
\
\
**Problem 2: Product Prices**\
prices = np.array([100, 250, 80, 120, 400, 60])\
**Tasks:**\
Extract all products costing more than 100.\
Extract all products costing less than 100.\
Extract the 2nd, 4th and 6th products using fancy indexing.

In [11]:
prices=np.array([100,250,80,120,400,60])
print("Products costing more than 100: ",prices[prices>100])
print("Products costing less than 100: ",prices[prices<100])
print("2nd, 4th and 6th products: ",prices[[1,3,5]])

Products costing more than 100:  [250 120 400]
Products costing less than 100:  [80 60]
2nd, 4th and 6th products:  [250 120  60]


\
\
\
**Problem 3: Temperature Monitoring**\
temps = np.array([32, 34, 35, 38, 40, 42, 37])\
**Tasks:**\
Get temperatures above 37.\
Get temperatures below 35.\
Reverse the dataset.

In [15]:
temps=np.array([32,34,35,38,40,42,37])
print("Temperatures above 37: ",temps[temps>37])
print("Temperatures below 35: ",temps[temps<35])
print("Reversed Dataset: ",temps[::-1])

Temperatures above 37:  [38 40 42]
Temperatures below 35:  [32 34]
Reversed Dataset:  [37 42 40 38 35 34 32]


\
\
\
**Problem 4: Employee IDs**\
employee_ids = np.array([101,102,103,104,105,106,107,108])\
**Tasks:**\
Extract IDs from position 2 to 6.\
Extract every second ID.\
Extract IDs at positions 1, 3 and 7.

In [19]:
employee_ids=np.array([101,102,103,104,105,106,107,108])
print("IDs from position 2 to 6: ", employee_ids[1:6])
print("Every second ID: ", employee_ids[1::2])
print("IDs at position 1, 3 and 7: ", employee_ids[[0,2,6]])

IDs from position 2 to 6:  [102 103 104 105 106]
Every second ID:  [102 104 106 108]
IDs at position 1, 3 and 7:  [101 103 107]


\
\
\
**Problem 5: Sales Data**\
sales = np.array([5000,7000,6500,9000,12000,11000])\
**Tasks:**\
Find all sales above 8000.\
Replace sales below 7000 with 0.\
Verify the shape, ndim, size and dtype.

In [25]:
sales=np.array([5000,7000,6500,9000,11000])
print("All sales above 8000: ",sales[sales>8000])
sales[sales<7000]=0
print("Sales after replacement: ",sales)
print("Shape of array: ",sales.shape)
print("Number of dimensions in array: ",sales.ndim)
print("Size of array: ",sales.size)
print("Datatype of array: ",sales.dtype)

All sales above 8000:  [ 9000 11000]
Sales after replacement:  [    0  7000     0  9000 11000]
Shape of array:  (5,)
Number of dimensions in array:  1
Size of array:  5
Datatype of array:  int64


\
\
\
**<center>Level 2: Data Cleaning Tasks (Intermediate)</center>**


\
**Problem 6: Customer Ages**\
ages = np.array([15,22,34,18,17,45,29,13,50])\
**Tasks:**\
Extract all adults.\
Extract all minors.\
Count visually how many adults remain after filtering.

In [32]:
ages=np.array([15,22,34,18,17,45,29,13,50])
adults=ages[ages>=18]
print("All adults: ",adults)
minors=ages[ages<18]
print("All minors: ",minors)

All adults:  [22 34 18 45 29 50]
All minors:  [15 17 13]


\
\
\
**Problem 7: E-commerce Orders**\
orders = np.array([\
    [101,500],\
    [102,1500],\
    [103,800],\
    [104,2500],\
    [105,300]\
])\
**Columns:**\
OrderID | Amount\
**Tasks:**\
Extract all order amounts.\
Extract orders with amount > 1000.\
Extract only the order IDs of high-value orders.

In [33]:
orders=np.array([
    [101,500],
    [102,1500],
    [103,800],
    [104,2500],
    [105,300]
])
print("All order amounts: ",orders[:,1])
high_value_orders=orders[orders[:,1]>1000]
print("All orders with amount > 1000: \n",high_value_orders)
print("Only IDs of orders with amount > 1000: \n",high_value_orders[:,0])

All order amounts:  [ 500 1500  800 2500  300]
All orders with amount > 1000: 
 [[ 102 1500]
 [ 104 2500]]
Only IDs of orders with amount > 1000: 
 [102 104]


\
\
\
**Problem 8: Student Scores**\
scores = np.array([\
    [78,85,90],\
    [45,50,55],\
    [88,92,95],\
    [60,65,70]\
])\
**Tasks:**\
Extract first student's scores.\
Extract Maths scores (column 0).\
Extract students whose Maths score is above 70.

In [34]:
scores = np.array([
[78,85,90],
[45,50,55],
[88,92,95],
[60,65,70]
])
student1=scores[0]
print("First Student's scores: ", student1)
maths=scores[:,0]
print("Maths Scores: ", maths)
students_with_greater_maths_score=scores[scores[:,0]>70]
print("Students whose maths score is above 70: \n", students_with_greater_maths_score)

First Student's scores:  [78 85 90]
Maths Scores:  [78 45 88 60]
Students whose maths score is above 70: 
 [[78 85 90]
 [88 92 95]]


\
\
\
**Problem 9: Hospital Patients**\
patients = np.array([\
    [1,25],\
    [2,67],\
    [3,43],\
    [4,80],\
    [5,15]\
])\
**Columns:**\
PatientID | Age\
**Tasks:**\
Extract senior citizens (60+).\
Extract patient IDs of seniors.\
Extract minors.

In [31]:
patients = np.array([
[1,25],
[2,67],
[3,43],
[4,80],
[5,15]
])
seniors=patients[patients[:,1]>=60]
print("Senior Citizens(60+): \n",seniors)
print("Patient IDs of seniors: ",seniors[:,0])
minors=patients[patients[:,1]<60]
print("Minor citizens: \n",minors)

Senior Citizens(60+): 
 [[ 2 67]
 [ 4 80]]
Patient IDs of seniors:  [2 4]
Minor citizens: 
 [[ 1 25]
 [ 3 43]
 [ 5 15]]


\
\
\
**Problem 10: Manufacturing Defects**\
defects = np.array([2,5,0,1,8,3,0])\
**Tasks:**\
Extract days with defects.\
Extract days with zero defects.\
Extract every alternate day.

In [41]:
defects = np.array([2,5,0,1,8,3,0])
days = np.array(["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"])
defect_days=days[defects>0]
print("Days with defect(s): ",defect_days)
no_defect_days=days[defects==0]
print("Days with zero defects: ",no_defect_days)
print("Defects every alternate day: ",defects[::2])

Days with defect(s):  ['Monday' 'Tuesday' 'Thursday' 'Friday' 'Saturday']
Days with zero defects:  ['Wednesday' 'Sunday']
Defects every alternate day:  [2 0 8 0]


\
\
\
**<center>Level 3: Real Dataset Manipulation (Upper Intermediate)</center>**


\
**Problem 11: Customer Dataset**\
customers = np.array([\
    ["Ali",22,50000],\
    ["Sara",25,70000],\
    ["Ahmed",30,90000],\
    ["Ayesha",21,45000],\
    ["Bilal",35,120000]\
], dtype=object)\
**Tasks:**\
Extract all names.\
Extract all salaries.\
Extract customers earning above 60000.\
Extract names of customers earning above 60000.

In [49]:
customers = np.array([
["Ali",22,50000],
["Sara",25,70000],
["Ahmed",30,90000],
["Ayesha",21,45000],
["Bilal",35,120000]
], dtype=object)
names = customers[:,0]
print("Names: ", names)
salaries = customers[:,2]
print("Salaries: ", salaries)
customers_earning_higher = customers[customers[:,2]>60000]
print("Customer data who earn greater than 60000: \n", customers_earning_higher)
names_of_customers_earning_higher = names[customers[:,2]>60000]
print("Names of customers earning higher than 60000: ", names_of_customers_earning_higher)

Names:  ['Ali' 'Sara' 'Ahmed' 'Ayesha' 'Bilal']
Salaries:  [50000 70000 90000 45000 120000]
Customer data who earn greater than 60000: 
 [['Sara' 25 70000]
 ['Ahmed' 30 90000]
 ['Bilal' 35 120000]]
Names of customers earning higher than 60000:  ['Sara' 'Ahmed' 'Bilal']


\
\
\
**Problem 12: Mobile App Analytics**\
downloads = np.array([\
    [1200,1500,1800,2200],\
    [1000,1100,1400,1700],\
    [2500,2700,3000,3300]\
]\
Rows = Apps\
Columns = Quarters\
**Tasks:**\
Extract Q2 downloads.\
Extract App 3 downloads.\
Extract last two quarters.

In [57]:
downloads = np.array([
[1200,1500,1800,2200],
[1000,1100,1400,1700],
[2500,2700,3000,3300]
])
Q2_downloads = downloads[:,1]
print("Quarter 2 downloads: ", Q2_downloads)
App3_downloads = downloads[2,:]
print("App 3 Downloads: ", App3_downloads)
Last_2Quarters = downloads[:,-2:]
print("Last 2 Quarters: \n",Last_2Quarters)

Quarter 2 downloads:  [1500 1100 2700]
App 3 Downloads:  [2500 2700 3000 3300]
Last 2 Quarters: 
 [[1800 2200]
 [1400 1700]
 [3000 3300]]


\
\
\
**Problem 13: Logistics Tracking**\
deliveries = np.array([\
    [1,2],\
    [2,5],\
    [3,1],\
    [4,8],\
    [5,3]\
])\
**Columns:**\
DeliveryID | DelayDays\
**Tasks:**\
Find delayed deliveries (>3 days).\
Extract Delivery IDs with delays.\
Extract on-time deliveries.

In [63]:
deliveries = np.array([
[1,2],
[2,5],
[3,1],
[4,8],
[5,3]
])
delayed_deliveries = deliveries[deliveries[:,1]>3]
print("Delayed Deliveries: \n",delayed_deliveries)
delayed_delivery_ids = deliveries[deliveries[:,1]>3,0]
print("IDs of delayed deliveries: ",delayed_delivery_ids)
ontime_deliveries = deliveries[deliveries[:,1]<=3]
print("On-time Deliveries: \n",ontime_deliveries)

Delayed Deliveries: 
 [[2 5]
 [4 8]]
IDs of delayed deliveries:  [2 4]
On-time Deliveries: 
 [[1 2]
 [3 1]
 [5 3]]


\
\
\
**Problem 14: Marketing Campaign**\
campaign = np.array([\
    [101,500],\
    [102,1200],\
    [103,300],\
    [104,2200],\
    [105,1800]\
])\
**Columns:**\
CampaignID | Leads\
**Tasks:**\
Extract campaigns generating >1000 leads.\
Extract their IDs.\
Extract campaigns generating <500 leads.

In [67]:
campaign = np.array([
[101,500],
[102,1200],
[103,300],
[104,2200],
[105,1800]
])
high_lead_campaigns = campaign[campaign[:,1]>1000]
print("Campaigns generating >1000 leads: \n",high_lead_campaigns)
print("IDs of high lead campaigns: ",high_lead_campaigns[:,0])
low_leads_campaigns = campaign[campaign[:,1]<500]
print("Campaigns generating <500 leads: \n",low_leads_campaigns)

Campaigns generating >1000 leads: 
 [[ 102 1200]
 [ 104 2200]
 [ 105 1800]]
IDs of high lead campaigns:  [102 104 105]
Campaigns generating <500 leads: 
 [[103 300]]


\
\
\
**Problem 15: Sensor Data**\
sensor = np.arange(1,101)\
**Tasks:**\
Extract first 20 readings.\
Extract last 20 readings.\
Extract every 5th reading.\
Reverse the readings.

In [74]:
sensor = np.arange(1,101)
print("First 20 readings: \n",sensor[:20])
print("Last 20 readings: \n", sensor[-20:])
print("Every 5th reading: \n",sensor[::5])
print("Reversed Readings: \n",sensor[::-1])

First 20 readings: 
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Last 20 readings: 
 [ 81  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98
  99 100]
Every 5th reading: 
 [ 1  6 11 16 21 26 31 36 41 46 51 56 61 66 71 76 81 86 91 96]
Reversed Readings: 
 [100  99  98  97  96  95  94  93  92  91  90  89  88  87  86  85  84  83
  82  81  80  79  78  77  76  75  74  73  72  71  70  69  68  67  66  65
  64  63  62  61  60  59  58  57  56  55  54  53  52  51  50  49  48  47
  46  45  44  43  42  41  40  39  38  37  36  35  34  33  32  31  30  29
  28  27  26  25  24  23  22  21  20  19  18  17  16  15  14  13  12  11
  10   9   8   7   6   5   4   3   2   1]


\
\
\
**<center>Level 4: Data Scientist Level (Advanced)</center>**

**Problem 16: Fraud Detection Preprocessing**\
transactions = np.array([\
    [1001,500],\
    [1002,25000],\
    [1003,700],\
    [1004,50000],\
    [1005,900]\
])\
**Columns:**\
TransactionID | Amount\
**Tasks:**\
Flag suspicious transactions (>10000).\
Extract suspicious IDs.\
Extract normal transactions.

In [77]:
transactions = np.array([
[1001,500],
[1002,25000],
[1003,700],
[1004,50000],
[1005,900]
])
suspicious = transactions[transactions[:,1]>10000]
print("Suspicious Transactions: \n", suspicious)
print("Suspicious IDs: ",suspicious[:,0])
normal = transactions[transactions[:,1]<=10000]
print("Normal Transactions: \n", normal)

Suspicious Transactions: 
 [[ 1002 25000]
 [ 1004 50000]]
Suspicious IDs:  [1002 1004]
Normal Transactions: 
 [[1001  500]
 [1003  700]
 [1005  900]]


\
\
\
**Problem 18: Retail Chain Analysis**\
stores = np.array([\
    [12000,15000,18000],\
    [8000,9000,9500],\
    [20000,22000,25000],\
    [5000,6000,7000]\
])\
**Tasks:**\
Extract high-performing stores (Month1 > 10000).\
Extract all sales data for those stores.\
Extract Month 3 sales.

In [3]:
stores = np.array([
[12000,15000,18000],
[8000,9000,9500],
[20000,22000,25000],
[5000,6000,7000]
])
high_performing_stores = stores[stores[:,0]>10000]
print("High Performing Stores(Month 1 > 10000): \n",high_performing_stores)
month3_sales = stores[:,2]
print("Month 3 Sales: ",month3_sales)

High Performing Stores(Month 1 > 10000): 
 [[12000 15000 18000]
 [20000 22000 25000]]
Month 3 Sales:  [18000  9500 25000  7000]


\
\
\
**Problem 19: Employee Retention Dataset**\
employees = np.array([\
    [1,2],\
    [2,5],\
    [3,1],\
    [4,8],\
    [5,6]\
])\
**Columns:**\
EmployeeID | YearsAtCompany\
**Tasks:**\
Extract employees with tenure ≥ 5.\
Extract their IDs.\
Extract employees with tenure < 3.

In [8]:
employees = np.array([
[1,2],
[2,5],
[3,1],
[4,8],
[5,6]
])
old_emps = employees[employees[:,1]>=5]
print("Employees with 5+ years: \n",old_emps)
old_emps_ids = old_emps[:,0]
print("Employee IDs with 5+ yrs: ",old_emps_ids)
new_emps = employees[employees[:,1]<3]
print("Employees with less than 3 yrs: \n",new_emps)

Employees with 5+ years: 
 [[2 5]
 [4 8]
 [5 6]]
Employee IDs with 5+ yrs:  [2 4 5]
Employees with less than 3 yrs: 
 [[1 2]
 [3 1]]


\
\
\
**Problem 20: Mini Data Science Case Study**\
A company dataset:\
data = np.array([\
       [101,22,50000],\
       [102,35,120000],\
       [103,19,25000],\
       [104,41,90000],\
       [105,28,70000],\
       [106,17,15000]\
])\
**Columns:**\
EmployeeID | Age | Salary\
**Without loops, solve:**\
Extract all adults.\
Extract employees earning > 60000.\
Extract employees aged between 20 and 40.\
Extract Employee IDs of high earners.\
Extract the Age and Salary columns only.\
Extract first 3 records.\
Extract last 2 records.\
Extract every alternate record.\
Reverse the entire dataset.\
Verify shape, ndim, size and dtype.

In [24]:
data = np.array([
[101,22,50000],
[102,35,120000],
[103,19,25000],
[104,41,90000],
[105,28,70000],
[106,17,15000]
])
adults = data[data[:,1]>=18]
print("Adults: \n",adults)
employees_earning_greater_than_60k = data[data[:,2]>60000]
print("Employees earning greater than 60k: \n",employees_earning_greater_than_60k)
employees_bw_20_and_40 = data[(data[:,1]>20) & (data[:,1]<40)]
print("Employees between ages 20 and 40: \n",employees_bw_20_and_40)
ids_of_high_earners = employees_earning_greater_than_60k[:,0]
print("IDs of high earners: ", ids_of_high_earners)
age_salary = data[:,1:]
print("Ages and Salaries only: \n",age_salary)
first_3records = data[:3]
print("First three records: \n",first_3records)
last_2records = data[-2:]
print("Last two records: \n", last_2records)
alternate_records = data[::2]
print("Alternate records: \n",alternate_records)
reversed_data = data[::-1]
print("Reversed dataset: \n", reversed_data)
print("Shape: ",data.shape)
print("Number of Dimensions: ",data.ndim)
print("Size: ",data.size)
print("DataType: ",data.dtype)

Adults: 
 [[   101     22  50000]
 [   102     35 120000]
 [   103     19  25000]
 [   104     41  90000]
 [   105     28  70000]]
Employees earning greater than 60k: 
 [[   102     35 120000]
 [   104     41  90000]
 [   105     28  70000]]
Employees between ages 20 and 40: 
 [[   101     22  50000]
 [   102     35 120000]
 [   105     28  70000]]
IDs of high earners:  [102 104 105]
Ages and Salaries only: 
 [[    22  50000]
 [    35 120000]
 [    19  25000]
 [    41  90000]
 [    28  70000]
 [    17  15000]]
First three records: 
 [[   101     22  50000]
 [   102     35 120000]
 [   103     19  25000]]
Last two records: 
 [[  105    28 70000]
 [  106    17 15000]]
Alternate records: 
 [[  101    22 50000]
 [  103    19 25000]
 [  105    28 70000]]
Reversed dataset: 
 [[   106     17  15000]
 [   105     28  70000]
 [   104     41  90000]
 [   103     19  25000]
 [   102     35 120000]
 [   101     22  50000]]
Shape:  (6, 3)
Number of Dimensions:  2
Size:  18
DataType:  int64
